/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package aplikasi.view;

import aplikasi.config.KoneksiDB;
import aplikasi.entity.Users;
import aplikasi.repository.RepoUsers;
import aplikasi.service.ServiceUsers;
import java.awt.event.KeyEvent;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author dhiskar
 */
public class LoginView extends javax.swing.JDialog {

    private final MainMenuView menuUtamaController;
    private final RepoUsers repoPengguna;
    int i = 3;

    /**
     * Creates new form LoginView
     */
    LoginView(MainMenuView menuUtama, java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        this.menuUtamaController = menuUtama;
        this.repoPengguna = new ServiceUsers(KoneksiDB.getDataSource());

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jToolBar1 = new javax.swing.JToolBar();
        btnLogin = new javax.swing.JButton();
        btnExit = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtxUsername = new javax.swing.JTextField();
        txtPassword = new javax.swing.JPasswordField();
        lbLimit = new javax.swing.JLabel();
        lbLimit1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setIconImage(new javax.swing.ImageIcon(getClass().getResource("/gambar/logo3.png")).getImage());
        setResizable(false);

        jToolBar1.setRollover(true);
        jToolBar1.setFocusable(false);
        jToolBar1.setMaximumSize(new java.awt.Dimension(218, 45));
        jToolBar1.setMinimumSize(new java.awt.Dimension(218, 45));
        jToolBar1.setPreferredSize(new java.awt.Dimension(100, 45));

        btnLogin.setText("Login");
        btnLogin.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnLogin.setMaximumSize(new java.awt.Dimension(100, 35));
        btnLogin.setMinimumSize(new java.awt.Dimension(100, 35));
        btnLogin.setPreferredSize(new java.awt.Dimension(100, 35));
        btnLogin.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLoginActionPerformed(evt);
            }
        });
        btnLogin.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                btnLoginKeyPressed(evt);
            }
        });
        jToolBar1.add(btnLogin);

        btnExit.setText("Kembali");
        btnExit.setFocusable(false);
        btnExit.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnExit.setMaximumSize(new java.awt.Dimension(100, 35));
        btnExit.setMinimumSize(new java.awt.Dimension(100, 35));
        btnExit.setPreferredSize(new java.awt.Dimension(100, 35));
        btnExit.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExitActionPerformed(evt);
            }
        });
        jToolBar1.add(btnExit);

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Login Aplikasi"));

        jLabel1.setText("Username");

        jLabel2.setText("Password");

        txtxUsername.setText("dhiskar");
        txtxUsername.setToolTipText("Isi dengan username");
        txtxUsername.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtxUsernameActionPerformed(evt);
            }
        });
        txtxUsername.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtxUsernameKeyPressed(evt);
            }
        });

        txtPassword.setText("Admin1");
        txtPassword.setToolTipText("Isi dengan password");
        txtPassword.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPasswordActionPerformed(evt);
            }
        });
        txtPassword.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtPasswordKeyPressed(evt);
            }
        });

        lbLimit.setForeground(new java.awt.Color(255, 0, 55));
        lbLimit.setText(" ");

        lbLimit1.setForeground(new java.awt.Color(255, 0, 0));
        lbLimit1.setText(" ");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(txtxUsername, javax.swing.GroupLayout.PREFERRED_SIZE, 331, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2))
                        .addGap(316, 316, 316))
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(lbLimit)
                        .addComponent(lbLimit1)
                        .addComponent(txtPassword, javax.swing.GroupLayout.PREFERRED_SIZE, 333, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(54, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtxUsername, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtPassword, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lbLimit1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lbLimit))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jToolBar1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jToolBar1, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExitActionPerformed
        this.dispose();
    }//GEN-LAST:event_btnExitActionPerformed

    private void txtxUsernameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtxUsernameActionPerformed
        txtxUsername.transferFocus();
    }//GEN-LAST:event_txtxUsernameActionPerformed

    private void txtxUsernameKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtxUsernameKeyPressed
        lbLimit.setText(" ");
        lbLimit1.setText(" ");
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            txtPassword.requestFocus();
        }
    }//GEN-LAST:event_txtxUsernameKeyPressed

    private void btnLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLoginActionPerformed
        try {
            char[] password = txtPassword.getPassword();
            Users pengguna = repoPengguna.findByUsernameAndPasswordAndIsStatusEnabled(txtxUsername.getText(), String.copyValueOf(password));
            this.menuUtamaController.setLoginEnabled(pengguna != null);
            if (pengguna != null && pengguna.getJabatan() == Users.Role.Admin && pengguna.getStatus()) {
                this.menuUtamaController.enabledMenu(true);
                this.menuUtamaController.setEnabledMenuAprovel(false);
                this.menuUtamaController.showUser(pengguna);
                this.menuUtamaController.daftarCaraPenggunaanAplikasi();
                this.menuUtamaController.daftarCaraPenggunaanAplikasi();
                this.dispose();
            } else if (pengguna != null && pengguna.getJabatan() == Users.Role.Gudang && pengguna.getStatus()) {
                this.menuUtamaController.enabledMenu(false);
                this.menuUtamaController.setEnabledMenuAset(false);
                this.menuUtamaController.setEnabledMenuKategoriAset(false);
                this.menuUtamaController.setEnabledMenuUser(false);
                this.menuUtamaController.setEnabledMenuPenambahan(true);
                this.menuUtamaController.setEnabledMenuPenghapusan(false);
                this.menuUtamaController.setEnabledMenuLaporan(false);
                this.menuUtamaController.setEnabledMenuAprovel(false);
                this.menuUtamaController.setEnabledMenuLaporanAsetMasuk(true);
                this.menuUtamaController.setEnabledMenuTentang(true);
                this.menuUtamaController.showUser(pengguna);
                this.menuUtamaController.daftarCaraPenggunaanAplikasi();
                this.dispose();
            } else if (pengguna != null && pengguna.getJabatan() == Users.Role.Kasir && pengguna.getStatus()) {
                this.menuUtamaController.enabledMenu(false);
                this.menuUtamaController.setEnabledMenuAset(false);
                this.menuUtamaController.setEnabledMenuKategoriAset(false);
                this.menuUtamaController.setEnabledMenuPenambahan(false);
                this.menuUtamaController.setEnabledMenuPenghapusan(true);
                this.menuUtamaController.setEnabledMenuPelanggan(false);
                this.menuUtamaController.setEnabledMenuLaporan(false);
                this.menuUtamaController.setEnabledMenuAprovel(false);
                this.menuUtamaController.setEnabledMenuLaporanAsetKeluar(true);
                this.menuUtamaController.setEnabledMenuTentang(true);
                this.menuUtamaController.showUser(pengguna);
                this.menuUtamaController.daftarCaraPenggunaanAplikasi();
                this.dispose();
            } else if (pengguna != null && pengguna.getJabatan() == Users.Role.Kepala && pengguna.getStatus()) {
                this.menuUtamaController.enabledMenu(false);
                this.menuUtamaController.setEnabledMenuAset(false);
                this.menuUtamaController.setEnabledMenuKategoriAset(false);
                this.menuUtamaController.setEnabledMenuPenambahan(false);
                this.menuUtamaController.setEnabledMenuPenghapusan(false);
                this.menuUtamaController.setEnabledMenuPelanggan(false);
                this.menuUtamaController.setEnabledMenuLaporan(true);
                this.menuUtamaController.setEnabledMenuAprovel(true);
                this.menuUtamaController.setEnabledMenuTentang(true);
                this.menuUtamaController.showUser(pengguna);
                this.menuUtamaController.daftarCaraPenggunaanAplikasi();
                this.dispose();
            } else {
                txtxUsername.selectAll();
                txtPassword.selectAll();
                txtxUsername.requestFocus();
                lbLimit1.setText("Username dan password salah atau tidak aktif !");
                lbLimit.setText(i + " upaya login tersisa..!");
                lbLimit.setVisible(true);
                i--;
                if (i == -1) {
                    JOptionPane.showMessageDialog(this, "Kesempatan login berakhir, \nSilahkan hubingi admin !", getTitle(), JOptionPane.WARNING_MESSAGE);
                    System.exit(0);
                }
            }
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(this, "Tidak ada sambungan ke database !", getTitle(), JOptionPane.ERROR_MESSAGE);
            Logger.getLogger(LoginView.class.getName()).log(Level.SEVERE, null, ex);
        }

    }//GEN-LAST:event_btnLoginActionPerformed

    private void txtPasswordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPasswordActionPerformed

    }//GEN-LAST:event_txtPasswordActionPerformed

    private void txtPasswordKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtPasswordKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            btnLoginActionPerformed(null);
        }
    }//GEN-LAST:event_txtPasswordKeyPressed

    private void btnLoginKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_btnLoginKeyPressed
        if (evt.getKeyCode()== KeyEvent.VK_ENTER) {
            btnLoginActionPerformed(null);
        }
    }//GEN-LAST:event_btnLoginKeyPressed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnExit;
    private javax.swing.JButton btnLogin;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JToolBar jToolBar1;
    private javax.swing.JLabel lbLimit;
    private javax.swing.JLabel lbLimit1;
    private javax.swing.JPasswordField txtPassword;
    private javax.swing.JTextField txtxUsername;
    // End of variables declaration//GEN-END:variables
}
