/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package aplikasi.view;

import aplikasi.entity.Users;
import aplikasi.view.menu.kepemilikan.DaftarKepemilikanView;
import aplikasi.view.menu.kepemilikan.DataKepemilikanView;
import aplikasi.view.menu.status.DaftarStatusView;
import aplikasi.view.menu.status.DataStatusAsetView;
import aplikasi.view.menu.user.DaftarUserView;
import aplikasi.view.menu.user.DataUserView;
import aplikasi.view.menu.aset.DaftarAsetView;
import aplikasi.view.menu.aset.DataAsetView;
import aplikasi.view.menu.kategori.DaftarKategoriView;
import aplikasi.view.menu.kategori.DataKategoriAset;
import aplikasi.view.menu.laporan.LaporanAset;
import aplikasi.view.menu.laporan.LaporanPeminjaman;
import aplikasi.view.menu.laporan.LaporanPengembalian;
import aplikasi.view.menu.laporan.LaporanSirkulasiAsetView;
import aplikasi.view.menu.lokasi.DaftarLokasiView;
import aplikasi.view.menu.lokasi.DataLokasiView;
import aplikasi.view.menu.peminjaman.DataPeminjamanView;
import aplikasi.view.menu.pengembalian.pinjaman.DataPengembalianView;
import aplikasi.view.menu.approval.ApprovalTransaksi;
import java.beans.PropertyVetoException;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JInternalFrame;

/**
 *
 * @author dhiskar
 */
public class MainMenuView extends javax.swing.JFrame {

    private Users p = null;

    /**
     * Creates new form MainMenuView
     */
    public MainMenuView() {
        initComponents();
        showTanggal();
        lblIdUser.setVisible(false);
//        mniUbahTransaksi.setVisible(false);
    }

    public void showTanggal() {
        Date d = new Date();
        SimpleDateFormat tanggal = new SimpleDateFormat("EEEE, dd MMMM yyyy");
        lblTanggal.setText(tanggal.format(d));
    }

    public void showLoginScreen() {
        LoginView login = new LoginView(this, this, true);
        login.setTitle("ASET DIES SORAYA- Application");
        login.setLocationRelativeTo(null);
        login.setVisible(true);
    }

    public void setInnerLayout(JInternalFrame internal) throws PropertyVetoException {
        this.desktop.removeAll();
        this.desktop.add(internal);
        internal.setMaximum(true);
        internal.setVisible(true);
        this.desktop.repaint();
    }

    public void showUser(Users p) {
        lblIdUser.setText(p.getId_user().toString());
        lblUser.setText(p.getUsername());
        lblJabatan.setText(p.getJabatan().toString());
        this.p = p;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuItem3 = new javax.swing.JMenuItem();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        lblUser = new javax.swing.JLabel();
        lblTanggal = new javax.swing.JLabel();
        lblIdUser = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        lblJabatan = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jToolBar1 = new javax.swing.JToolBar();
        btnUsers = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JToolBar.Separator();
        jSeparator2 = new javax.swing.JToolBar.Separator();
        btnAset = new javax.swing.JButton();
        btnKategoriAset = new javax.swing.JButton();
        txtKepemilikan = new javax.swing.JButton();
        btnLokasi = new javax.swing.JButton();
        btnStatus = new javax.swing.JButton();
        jSeparator3 = new javax.swing.JToolBar.Separator();
        jSeparator9 = new javax.swing.JToolBar.Separator();
        btnPeminjamanAset = new javax.swing.JButton();
        btnPengembalianAset = new javax.swing.JButton();
        jSeparator12 = new javax.swing.JToolBar.Separator();
        jSeparator6 = new javax.swing.JToolBar.Separator();
        btnPersetujuanTransaksi = new javax.swing.JButton();
        desktop = new javax.swing.JDesktopPane();
        jMenuBar1 = new javax.swing.JMenuBar();
        mnuAplikasi = new javax.swing.JMenu();
        mniLogin = new javax.swing.JMenuItem();
        mniLogout = new javax.swing.JMenuItem();
        jSeparator4 = new javax.swing.JPopupMenu.Separator();
        mniExit = new javax.swing.JMenuItem();
        mnuMasterData = new javax.swing.JMenu();
        mniUsers = new javax.swing.JMenuItem();
        jSeparator5 = new javax.swing.JPopupMenu.Separator();
        mniAset = new javax.swing.JMenuItem();
        mniKategoriAset = new javax.swing.JMenuItem();
        mniKepemilikan = new javax.swing.JMenuItem();
        mniLokasi = new javax.swing.JMenuItem();
        mniStatus = new javax.swing.JMenuItem();
        mnuTransaksi = new javax.swing.JMenu();
        mniPeminjamanAset = new javax.swing.JMenuItem();
        mniPengembalianAset = new javax.swing.JMenuItem();
        jSeparator11 = new javax.swing.JPopupMenu.Separator();
        mniPersetujuanTransaksi = new javax.swing.JMenuItem();
        mniLaporan = new javax.swing.JMenu();
        mniLapDataAset = new javax.swing.JMenuItem();
        jSeparator8 = new javax.swing.JPopupMenu.Separator();
        mniLapPeminjamanAset = new javax.swing.JMenuItem();
        mniLapPengembalianAset = new javax.swing.JMenuItem();
        jSeparator10 = new javax.swing.JPopupMenu.Separator();
        mniLapSirkulasiAset = new javax.swing.JMenuItem();
        jMenu1 = new javax.swing.JMenu();
        mniTentangAplikasi = new javax.swing.JMenuItem();

        jMenuItem3.setText("jMenuItem3");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setIconImage(new javax.swing.ImageIcon(getClass().getResource("/gambar/logo3.png")).getImage());
        setMinimumSize(new java.awt.Dimension(1024, 600));

        jPanel1.setPreferredSize(new java.awt.Dimension(624, 40));

        jLabel1.setFont(new java.awt.Font("Dialog", 2, 12)); // NOI18N
        jLabel1.setText("Login by :");

        lblUser.setFont(new java.awt.Font("Dialog", 2, 12)); // NOI18N
        lblUser.setText("null");
        lblUser.setToolTipText("Username pengguna yang login");

        lblTanggal.setFont(new java.awt.Font("Dialog", 2, 12)); // NOI18N
        lblTanggal.setText("null");

        lblIdUser.setFont(new java.awt.Font("Dialog", 2, 12)); // NOI18N
        lblIdUser.setText("-");

        jLabel2.setFont(new java.awt.Font("Dialog", 2, 12)); // NOI18N
        jLabel2.setText("|");

        lblJabatan.setFont(new java.awt.Font("Dialog", 2, 12)); // NOI18N
        lblJabatan.setText("null");
        lblJabatan.setToolTipText("Jabatan");

        jLabel3.setFont(new java.awt.Font("Dialog", 2, 12)); // NOI18N
        jLabel3.setText(" (");

        jLabel4.setFont(new java.awt.Font("Dialog", 2, 12)); // NOI18N
        jLabel4.setText(")");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblIdUser)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblUser)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblJabatan)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 13, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 3, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblTanggal)
                .addContainerGap(476, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(13, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel3)
                        .addComponent(lblJabatan)
                        .addComponent(jLabel4))
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel1)
                        .addComponent(lblUser)
                        .addComponent(lblTanggal)
                        .addComponent(lblIdUser)
                        .addComponent(jLabel2)))
                .addContainerGap())
        );

        getContentPane().add(jPanel1, java.awt.BorderLayout.PAGE_END);

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder("Main Menu"));
        jPanel3.setPreferredSize(new java.awt.Dimension(215, 270));

        jToolBar1.setOrientation(javax.swing.SwingConstants.VERTICAL);
        jToolBar1.setRollover(true);
        jToolBar1.setPreferredSize(new java.awt.Dimension(209, 328));

        btnUsers.setText("User / Pengguna");
        btnUsers.setToolTipText("Tambah data user baru");
        btnUsers.setEnabled(false);
        btnUsers.setFocusable(false);
        btnUsers.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnUsers.setMaximumSize(new java.awt.Dimension(200, 35));
        btnUsers.setMinimumSize(new java.awt.Dimension(200, 35));
        btnUsers.setPreferredSize(new java.awt.Dimension(200, 35));
        btnUsers.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnUsers.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUsersActionPerformed(evt);
            }
        });
        jToolBar1.add(btnUsers);
        jToolBar1.add(jSeparator1);
        jToolBar1.add(jSeparator2);

        btnAset.setText("Aset Dies");
        btnAset.setToolTipText("Tambah data aset baru");
        btnAset.setEnabled(false);
        btnAset.setFocusable(false);
        btnAset.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnAset.setMaximumSize(new java.awt.Dimension(200, 35));
        btnAset.setMinimumSize(new java.awt.Dimension(200, 35));
        btnAset.setPreferredSize(new java.awt.Dimension(200, 35));
        btnAset.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnAset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAsetActionPerformed(evt);
            }
        });
        jToolBar1.add(btnAset);

        btnKategoriAset.setText("Kategori Dies");
        btnKategoriAset.setToolTipText("Tambah data kategori baru");
        btnKategoriAset.setEnabled(false);
        btnKategoriAset.setFocusable(false);
        btnKategoriAset.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnKategoriAset.setMaximumSize(new java.awt.Dimension(200, 35));
        btnKategoriAset.setMinimumSize(new java.awt.Dimension(200, 35));
        btnKategoriAset.setPreferredSize(new java.awt.Dimension(200, 35));
        btnKategoriAset.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnKategoriAset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnKategoriAsetActionPerformed(evt);
            }
        });
        jToolBar1.add(btnKategoriAset);

        txtKepemilikan.setText("Kepemilikan Dies");
        txtKepemilikan.setToolTipText("Tambah data kepemilikan baru");
        txtKepemilikan.setEnabled(false);
        txtKepemilikan.setFocusable(false);
        txtKepemilikan.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        txtKepemilikan.setMaximumSize(new java.awt.Dimension(200, 35));
        txtKepemilikan.setMinimumSize(new java.awt.Dimension(200, 35));
        txtKepemilikan.setPreferredSize(new java.awt.Dimension(200, 35));
        txtKepemilikan.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        txtKepemilikan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtKepemilikanActionPerformed(evt);
            }
        });
        jToolBar1.add(txtKepemilikan);

        btnLokasi.setText("Lokasi Dies");
        btnLokasi.setToolTipText("Tambah data lokasi baru");
        btnLokasi.setEnabled(false);
        btnLokasi.setFocusable(false);
        btnLokasi.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnLokasi.setMaximumSize(new java.awt.Dimension(200, 35));
        btnLokasi.setMinimumSize(new java.awt.Dimension(200, 35));
        btnLokasi.setPreferredSize(new java.awt.Dimension(200, 35));
        btnLokasi.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnLokasi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLokasiActionPerformed(evt);
            }
        });
        jToolBar1.add(btnLokasi);

        btnStatus.setText("Status Dies");
        btnStatus.setToolTipText("Tambah data status baru");
        btnStatus.setEnabled(false);
        btnStatus.setFocusable(false);
        btnStatus.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnStatus.setMaximumSize(new java.awt.Dimension(200, 35));
        btnStatus.setMinimumSize(new java.awt.Dimension(200, 35));
        btnStatus.setPreferredSize(new java.awt.Dimension(200, 35));
        btnStatus.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnStatus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnStatusActionPerformed(evt);
            }
        });
        jToolBar1.add(btnStatus);
        jToolBar1.add(jSeparator3);
        jToolBar1.add(jSeparator9);

        btnPeminjamanAset.setForeground(new java.awt.Color(0, 110, 4));
        btnPeminjamanAset.setText("Peminjaman Aset Dies");
        btnPeminjamanAset.setToolTipText("Buka transaksi pengembalian aset");
        btnPeminjamanAset.setEnabled(false);
        btnPeminjamanAset.setFocusable(false);
        btnPeminjamanAset.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnPeminjamanAset.setMaximumSize(new java.awt.Dimension(200, 35));
        btnPeminjamanAset.setMinimumSize(new java.awt.Dimension(200, 35));
        btnPeminjamanAset.setPreferredSize(new java.awt.Dimension(200, 35));
        btnPeminjamanAset.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnPeminjamanAset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPeminjamanAsetActionPerformed(evt);
            }
        });
        jToolBar1.add(btnPeminjamanAset);

        btnPengembalianAset.setForeground(new java.awt.Color(0, 2, 255));
        btnPengembalianAset.setText("Pengembalian Aset Dies");
        btnPengembalianAset.setToolTipText("Buka transaksi pengembalian aset");
        btnPengembalianAset.setEnabled(false);
        btnPengembalianAset.setFocusable(false);
        btnPengembalianAset.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnPengembalianAset.setMaximumSize(new java.awt.Dimension(200, 35));
        btnPengembalianAset.setMinimumSize(new java.awt.Dimension(200, 35));
        btnPengembalianAset.setPreferredSize(new java.awt.Dimension(200, 35));
        btnPengembalianAset.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnPengembalianAset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPengembalianAsetActionPerformed(evt);
            }
        });
        jToolBar1.add(btnPengembalianAset);
        jToolBar1.add(jSeparator12);
        jToolBar1.add(jSeparator6);

        btnPersetujuanTransaksi.setForeground(new java.awt.Color(0, 2, 255));
        btnPersetujuanTransaksi.setText("Approval Transaksi");
        btnPersetujuanTransaksi.setToolTipText("");
        btnPersetujuanTransaksi.setEnabled(false);
        btnPersetujuanTransaksi.setFocusable(false);
        btnPersetujuanTransaksi.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnPersetujuanTransaksi.setMaximumSize(new java.awt.Dimension(200, 35));
        btnPersetujuanTransaksi.setMinimumSize(new java.awt.Dimension(200, 35));
        btnPersetujuanTransaksi.setPreferredSize(new java.awt.Dimension(200, 35));
        btnPersetujuanTransaksi.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnPersetujuanTransaksi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPersetujuanTransaksiActionPerformed(evt);
            }
        });
        jToolBar1.add(btnPersetujuanTransaksi);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addComponent(jToolBar1, javax.swing.GroupLayout.PREFERRED_SIZE, 199, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addComponent(jToolBar1, javax.swing.GroupLayout.PREFERRED_SIZE, 457, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel3, java.awt.BorderLayout.LINE_START);

        javax.swing.GroupLayout desktopLayout = new javax.swing.GroupLayout(desktop);
        desktop.setLayout(desktopLayout);
        desktopLayout.setHorizontalGroup(
            desktopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 462, Short.MAX_VALUE)
        );
        desktopLayout.setVerticalGroup(
            desktopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 479, Short.MAX_VALUE)
        );

        getContentPane().add(desktop, java.awt.BorderLayout.CENTER);

        jMenuBar1.setMinimumSize(new java.awt.Dimension(320, 35));
        jMenuBar1.setPreferredSize(new java.awt.Dimension(320, 35));

        mnuAplikasi.setText("Aplikasi");

        mniLogin.setText("Login");
        mniLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mniLoginActionPerformed(evt);
            }
        });
        mnuAplikasi.add(mniLogin);

        mniLogout.setText("Logout");
        mniLogout.setEnabled(false);
        mniLogout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mniLogoutActionPerformed(evt);
            }
        });
        mnuAplikasi.add(mniLogout);
        mnuAplikasi.add(jSeparator4);

        mniExit.setForeground(new java.awt.Color(253, 0, 3));
        mniExit.setText("Exit");
        mniExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mniExitActionPerformed(evt);
            }
        });
        mnuAplikasi.add(mniExit);

        jMenuBar1.add(mnuAplikasi);

        mnuMasterData.setText("Master Data");

        mniUsers.setText("User");
        mniUsers.setEnabled(false);
        mniUsers.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mniUsersActionPerformed(evt);
            }
        });
        mnuMasterData.add(mniUsers);
        mnuMasterData.add(jSeparator5);

        mniAset.setText("Aset");
        mniAset.setEnabled(false);
        mniAset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mniAsetActionPerformed(evt);
            }
        });
        mnuMasterData.add(mniAset);

        mniKategoriAset.setText("Kategori");
        mniKategoriAset.setEnabled(false);
        mniKategoriAset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mniKategoriAsetActionPerformed(evt);
            }
        });
        mnuMasterData.add(mniKategoriAset);

        mniKepemilikan.setText("Kepemilikan");
        mniKepemilikan.setEnabled(false);
        mniKepemilikan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mniKepemilikanActionPerformed(evt);
            }
        });
        mnuMasterData.add(mniKepemilikan);

        mniLokasi.setText("Lokasi");
        mniLokasi.setEnabled(false);
        mniLokasi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mniLokasiActionPerformed(evt);
            }
        });
        mnuMasterData.add(mniLokasi);

        mniStatus.setText("Status");
        mniStatus.setEnabled(false);
        mniStatus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mniStatusActionPerformed(evt);
            }
        });
        mnuMasterData.add(mniStatus);

        jMenuBar1.add(mnuMasterData);

        mnuTransaksi.setText("Transaksi");

        mniPeminjamanAset.setForeground(new java.awt.Color(0, 110, 4));
        mniPeminjamanAset.setText("Peminjaman Aset");
        mniPeminjamanAset.setEnabled(false);
        mniPeminjamanAset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mniPeminjamanAsetActionPerformed(evt);
            }
        });
        mnuTransaksi.add(mniPeminjamanAset);

        mniPengembalianAset.setForeground(new java.awt.Color(0, 2, 255));
        mniPengembalianAset.setText("Pengembalian Aset");
        mniPengembalianAset.setEnabled(false);
        mniPengembalianAset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mniPengembalianAsetActionPerformed(evt);
            }
        });
        mnuTransaksi.add(mniPengembalianAset);
        mnuTransaksi.add(jSeparator11);

        mniPersetujuanTransaksi.setText("Approval Transaksi");
        mniPersetujuanTransaksi.setEnabled(false);
        mniPersetujuanTransaksi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mniPersetujuanTransaksiActionPerformed(evt);
            }
        });
        mnuTransaksi.add(mniPersetujuanTransaksi);

        jMenuBar1.add(mnuTransaksi);

        mniLaporan.setText("Laporan");
        mniLaporan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mniLaporanActionPerformed(evt);
            }
        });

        mniLapDataAset.setText("Aset");
        mniLapDataAset.setEnabled(false);
        mniLapDataAset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mniLapDataAsetActionPerformed(evt);
            }
        });
        mniLaporan.add(mniLapDataAset);
        mniLaporan.add(jSeparator8);

        mniLapPeminjamanAset.setForeground(new java.awt.Color(0, 110, 4));
        mniLapPeminjamanAset.setText("Peminjaman Aset");
        mniLapPeminjamanAset.setEnabled(false);
        mniLapPeminjamanAset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mniLapPeminjamanAsetActionPerformed(evt);
            }
        });
        mniLaporan.add(mniLapPeminjamanAset);

        mniLapPengembalianAset.setForeground(new java.awt.Color(0, 2, 255));
        mniLapPengembalianAset.setText("Pengembalian Aset");
        mniLapPengembalianAset.setEnabled(false);
        mniLapPengembalianAset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mniLapPengembalianAsetActionPerformed(evt);
            }
        });
        mniLaporan.add(mniLapPengembalianAset);
        mniLaporan.add(jSeparator10);

        mniLapSirkulasiAset.setText("Sirkulasi Aset");
        mniLapSirkulasiAset.setEnabled(false);
        mniLapSirkulasiAset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mniLapSirkulasiAsetActionPerformed(evt);
            }
        });
        mniLaporan.add(mniLapSirkulasiAset);

        jMenuBar1.add(mniLaporan);

        jMenu1.setText("Tentang");
        jMenu1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenu1ActionPerformed(evt);
            }
        });

        mniTentangAplikasi.setText("Tentang Aplikasi");
        mniTentangAplikasi.setEnabled(false);
        mniTentangAplikasi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mniTentangAplikasiActionPerformed(evt);
            }
        });
        jMenu1.add(mniTentangAplikasi);

        jMenuBar1.add(jMenu1);

        setJMenuBar(jMenuBar1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void mniLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mniLoginActionPerformed
        showLoginScreen();
    }//GEN-LAST:event_mniLoginActionPerformed

    private void mniExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mniExitActionPerformed
        System.exit(0);
    }//GEN-LAST:event_mniExitActionPerformed

    private void mniAsetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mniAsetActionPerformed
        try {
            DaftarAsetView view = new DaftarAsetView(this, p);
            setInnerLayout(view);
        } catch (Exception e) {
            Logger.getLogger(MainMenuView.class.getName()).log(Level.SEVERE, null, e);
        }
    }//GEN-LAST:event_mniAsetActionPerformed
    public void daftarCaraPenggunaanAplikasi() {
        try {
            TentangAplikasi view = new TentangAplikasi(this);
            setInnerLayout(view);
        } catch (Exception e) {
            Logger.getLogger(MainMenuView.class.getName()).log(Level.SEVERE, null, e);
        }
    }

    private void mniUsersActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mniUsersActionPerformed
        try {
            DaftarUserView view = new DaftarUserView(this);
            setInnerLayout(view);
        } catch (Exception e) {
            Logger.getLogger(MainMenuView.class.getName()).log(Level.SEVERE, null, e);
        }
    }//GEN-LAST:event_mniUsersActionPerformed

    private void mniKepemilikanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mniKepemilikanActionPerformed
        try {
            DaftarKepemilikanView view = new DaftarKepemilikanView(this);
            setInnerLayout(view);
        } catch (Exception e) {
            Logger.getLogger(MainMenuView.class.getName()).log(Level.SEVERE, null, e);
        }
    }//GEN-LAST:event_mniKepemilikanActionPerformed

    private void mniKategoriAsetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mniKategoriAsetActionPerformed
        try {
            DaftarKategoriView view = new DaftarKategoriView(this);
            setInnerLayout(view);
        } catch (Exception e) {
            Logger.getLogger(MainMenuView.class.getName()).log(Level.SEVERE, null, e);
        }
    }//GEN-LAST:event_mniKategoriAsetActionPerformed

    private void mniLokasiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mniLokasiActionPerformed
        try {
            DaftarLokasiView view = new DaftarLokasiView(this);
            setInnerLayout(view);
        } catch (Exception e) {
            Logger.getLogger(MainMenuView.class.getName()).log(Level.SEVERE, null, e);
        }
    }//GEN-LAST:event_mniLokasiActionPerformed

    private void mniStatusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mniStatusActionPerformed
        try {
            DaftarStatusView view = new DaftarStatusView(this);
            setInnerLayout(view);
        } catch (Exception e) {
            Logger.getLogger(MainMenuView.class.getName()).log(Level.SEVERE, null, e);
        }
    }//GEN-LAST:event_mniStatusActionPerformed

    private void mniLapPengembalianAsetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mniLapPengembalianAsetActionPerformed
        try {
            LaporanPengembalian view = new LaporanPengembalian(this, p);
            setInnerLayout(view);
        } catch (PropertyVetoException ex) {
            Logger.getLogger(MainMenuView.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_mniLapPengembalianAsetActionPerformed

    private void mniLogoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mniLogoutActionPerformed
        this.setLoginEnabled(false);
        this.enabledMenu(false);
        this.desktop.removeAll();
        this.desktop.repaint();
        lblUser.setText("null");
        lblJabatan.setText("null");
        mniLoginActionPerformed(null);
    }//GEN-LAST:event_mniLogoutActionPerformed

    private void jMenu1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenu1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenu1ActionPerformed

    private void mniTentangAplikasiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mniTentangAplikasiActionPerformed
        try {
            TentangAplikasi view = new TentangAplikasi(this);
            setInnerLayout(view);
        } catch (Exception e) {
            Logger.getLogger(MainMenuView.class.getName()).log(Level.SEVERE, null, e);
        }

    }//GEN-LAST:event_mniTentangAplikasiActionPerformed

    private void mniPengembalianAsetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mniPengembalianAsetActionPerformed
        try {
            DataPengembalianView view = new DataPengembalianView(this, p);
            setInnerLayout(view);
        } catch (PropertyVetoException ex) {
            Logger.getLogger(MainMenuView.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_mniPengembalianAsetActionPerformed

    private void mniPeminjamanAsetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mniPeminjamanAsetActionPerformed
        try {
            DataPeminjamanView view = new DataPeminjamanView(this, p);
            setInnerLayout(view);
        } catch (PropertyVetoException ex) {
            Logger.getLogger(MainMenuView.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_mniPeminjamanAsetActionPerformed

    private void mniLaporanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mniLaporanActionPerformed
    }//GEN-LAST:event_mniLaporanActionPerformed

    private void mniLapSirkulasiAsetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mniLapSirkulasiAsetActionPerformed
        try {
            LaporanSirkulasiAsetView view = new LaporanSirkulasiAsetView(this, p);
            setInnerLayout(view);
        } catch (Exception ex) {
            Logger.getLogger(MainMenuView.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_mniLapSirkulasiAsetActionPerformed

    private void mniLapDataAsetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mniLapDataAsetActionPerformed
        try {
            LaporanAset view = new LaporanAset(this, p);
            setInnerLayout(view);
        } catch (Exception ex) {
            Logger.getLogger(MainMenuView.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_mniLapDataAsetActionPerformed

    private void btnPeminjamanAsetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPeminjamanAsetActionPerformed
        try {
            DataPeminjamanView view = new DataPeminjamanView(this, p);
            setInnerLayout(view);
        } catch (Exception e) {
            Logger.getLogger(MainMenuView.class.getName()).log(Level.SEVERE, null, e);
        }
    }//GEN-LAST:event_btnPeminjamanAsetActionPerformed

    private void btnPengembalianAsetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPengembalianAsetActionPerformed
        try {
            DataPengembalianView view = new DataPengembalianView(this, p);
            setInnerLayout(view);
        } catch (Exception e) {
            Logger.getLogger(MainMenuView.class.getName()).log(Level.SEVERE, null, e);
        }
    }//GEN-LAST:event_btnPengembalianAsetActionPerformed

    private void btnStatusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnStatusActionPerformed
        DataStatusAsetView view = new DataStatusAsetView(this, true);
        view.setLocationRelativeTo(null);
        view.setResizable(false);
        view.setVisible(true);
    }//GEN-LAST:event_btnStatusActionPerformed

    private void btnLokasiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLokasiActionPerformed
        DataLokasiView view = new DataLokasiView(this, true);
        view.setLocationRelativeTo(null);
        view.setResizable(false);
        view.setVisible(true);
        // TODO add your handling code here:
    }//GEN-LAST:event_btnLokasiActionPerformed

    private void btnKategoriAsetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnKategoriAsetActionPerformed
        DataKategoriAset ka = new DataKategoriAset(this, true);
        ka.setLocationRelativeTo(null);
        ka.setResizable(false);
        ka.setVisible(true);
    }//GEN-LAST:event_btnKategoriAsetActionPerformed

    private void btnAsetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAsetActionPerformed
        DataAsetView aset = new DataAsetView(this, true, p);
        aset.setLocationRelativeTo(null);
        aset.setResizable(false);
        aset.setVisible(true);
    }//GEN-LAST:event_btnAsetActionPerformed

    private void btnUsersActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUsersActionPerformed
        DataUserView u = new DataUserView(this, true);
        u.setLocationRelativeTo(null);
        u.setResizable(false);
        u.setVisible(true);
    }//GEN-LAST:event_btnUsersActionPerformed

    private void txtKepemilikanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtKepemilikanActionPerformed
        DataKepemilikanView kepemilikan = new DataKepemilikanView(this, true);
        kepemilikan.setLocationRelativeTo(null);
        kepemilikan.setResizable(false);
        kepemilikan.setVisible(true);
    }//GEN-LAST:event_txtKepemilikanActionPerformed

    private void mniLapPeminjamanAsetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mniLapPeminjamanAsetActionPerformed
        try {
            LaporanPeminjaman view = new LaporanPeminjaman(this, p);
            setInnerLayout(view);
        } catch (PropertyVetoException ex) {
            Logger.getLogger(MainMenuView.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_mniLapPeminjamanAsetActionPerformed

    private void mniPersetujuanTransaksiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mniPersetujuanTransaksiActionPerformed
        try {
            ApprovalTransaksi view = new ApprovalTransaksi(this, p);
            setInnerLayout(view);
        } catch (PropertyVetoException ex) {
            Logger.getLogger(MainMenuView.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_mniPersetujuanTransaksiActionPerformed

    private void btnPersetujuanTransaksiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPersetujuanTransaksiActionPerformed
       try {
            ApprovalTransaksi view = new ApprovalTransaksi(this, p);
            setInnerLayout(view);
        } catch (PropertyVetoException ex) {
            Logger.getLogger(MainMenuView.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnPersetujuanTransaksiActionPerformed

    public void setEnabledMenuPelanggan(Boolean aktif) {
        this.txtKepemilikan.setEnabled(aktif);
        this.mniKepemilikan.setEnabled(aktif);
    }

    public void setEnabledMenuUser(Boolean aktif) {
        this.btnUsers.setEnabled(aktif);
        this.mniUsers.setEnabled(aktif);
    }

    public void setEnabledMenuHapusTransaksi(Boolean aktif) {
        this.btnUsers.setEnabled(aktif);
        this.mniUsers.setEnabled(aktif);
    }

    public void setEnabledMenuKategoriAset(Boolean aktif) {
        this.btnKategoriAset.setEnabled(aktif);
        this.mniKategoriAset.setEnabled(aktif);
    }

    public void setEnabledMenuAset(Boolean aktif) {
        this.btnAset.setEnabled(aktif);
        this.mniAset.setEnabled(aktif);
    }

    public void setEnabledMenuPenghapusan(Boolean aktif) {

        this.btnPeminjamanAset.setEnabled(aktif);
        this.mniPeminjamanAset.setEnabled(aktif);
    }

    public void setEnabledMenuPenambahan(Boolean aktif) {

        this.btnPengembalianAset.setEnabled(aktif);
        this.mniPengembalianAset.setEnabled(aktif);
    }

    public void setEnabledMenuLaporan(Boolean aktif) {
        this.mniLapDataAset.setEnabled(aktif);
        this.mniLapPeminjamanAset.setEnabled(aktif);
        this.mniLapPengembalianAset.setEnabled(aktif);
        this.mniLapSirkulasiAset.setEnabled(aktif);
    }

    public void setEnabledMenuLaporanAsetKeluar(Boolean aktif) {
        this.mniLapDataAset.setEnabled(aktif);
        this.mniLapPeminjamanAset.setEnabled(aktif);
    }

    public void setEnabledMenuLaporanAsetMasuk(Boolean aktif) {
        this.mniLapDataAset.setEnabled(aktif);
        this.mniLapPengembalianAset.setEnabled(aktif);
    }

    public void setEnabledMenuTentang(boolean aktif) {
        this.mniTentangAplikasi.setEnabled(aktif);
    }

    public void setLoginEnabled(Boolean login) {
        if (login) {
            this.mniLogin.setEnabled(false);
            this.mniLogout.setEnabled(true);
        } else {
            this.mniLogin.setEnabled(true);
            this.mniLogout.setEnabled(false);
        }
    }

    public void setEnabledMenuAprovel(boolean aktif) {
        this.btnPersetujuanTransaksi.setEnabled(aktif);
        this.mniPersetujuanTransaksi.setEnabled(aktif);
    }

    public void enabledMenu(Boolean aktif) {
        this.txtKepemilikan.setEnabled(aktif);
        this.btnUsers.setEnabled(aktif);
        this.btnKategoriAset.setEnabled(aktif);
        this.btnAset.setEnabled(aktif);
        this.btnLokasi.setEnabled(aktif);
        this.btnStatus.setEnabled(aktif);

        this.btnPeminjamanAset.setEnabled(aktif);
        this.btnPengembalianAset.setEnabled(aktif);
        this.btnPersetujuanTransaksi.setEnabled(aktif);

        this.mniKepemilikan.setEnabled(aktif);
        this.mniUsers.setEnabled(aktif);
        this.mniAset.setEnabled(aktif);
        this.mniKategoriAset.setEnabled(aktif);
        this.mniLokasi.setEnabled(aktif);
        this.mniStatus.setEnabled(aktif);
        this.mniPeminjamanAset.setEnabled(aktif);
        this.mniPengembalianAset.setEnabled(aktif);
        this.mniPersetujuanTransaksi.setEnabled(aktif);

        this.mniLapDataAset.setEnabled(aktif);
        this.mniLapPeminjamanAset.setEnabled(aktif);
        this.mniLapPengembalianAset.setEnabled(aktif);
        this.mniLapSirkulasiAset.setEnabled(aktif);

        this.mniTentangAplikasi.setEnabled(aktif);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAset;
    private javax.swing.JButton btnKategoriAset;
    private javax.swing.JButton btnLokasi;
    private javax.swing.JButton btnPeminjamanAset;
    private javax.swing.JButton btnPengembalianAset;
    private javax.swing.JButton btnPersetujuanTransaksi;
    private javax.swing.JButton btnStatus;
    private javax.swing.JButton btnUsers;
    private javax.swing.JDesktopPane desktop;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JToolBar.Separator jSeparator1;
    private javax.swing.JPopupMenu.Separator jSeparator10;
    private javax.swing.JPopupMenu.Separator jSeparator11;
    private javax.swing.JToolBar.Separator jSeparator12;
    private javax.swing.JToolBar.Separator jSeparator2;
    private javax.swing.JToolBar.Separator jSeparator3;
    private javax.swing.JPopupMenu.Separator jSeparator4;
    private javax.swing.JPopupMenu.Separator jSeparator5;
    private javax.swing.JToolBar.Separator jSeparator6;
    private javax.swing.JPopupMenu.Separator jSeparator8;
    private javax.swing.JToolBar.Separator jSeparator9;
    private javax.swing.JToolBar jToolBar1;
    private javax.swing.JLabel lblIdUser;
    private javax.swing.JLabel lblJabatan;
    private javax.swing.JLabel lblTanggal;
    private javax.swing.JLabel lblUser;
    private javax.swing.JMenuItem mniAset;
    private javax.swing.JMenuItem mniExit;
    private javax.swing.JMenuItem mniKategoriAset;
    private javax.swing.JMenuItem mniKepemilikan;
    private javax.swing.JMenuItem mniLapDataAset;
    private javax.swing.JMenuItem mniLapPeminjamanAset;
    private javax.swing.JMenuItem mniLapPengembalianAset;
    private javax.swing.JMenuItem mniLapSirkulasiAset;
    private javax.swing.JMenu mniLaporan;
    private javax.swing.JMenuItem mniLogin;
    private javax.swing.JMenuItem mniLogout;
    private javax.swing.JMenuItem mniLokasi;
    private javax.swing.JMenuItem mniPeminjamanAset;
    private javax.swing.JMenuItem mniPengembalianAset;
    private javax.swing.JMenuItem mniPersetujuanTransaksi;
    private javax.swing.JMenuItem mniStatus;
    private javax.swing.JMenuItem mniTentangAplikasi;
    private javax.swing.JMenuItem mniUsers;
    private javax.swing.JMenu mnuAplikasi;
    private javax.swing.JMenu mnuMasterData;
    private javax.swing.JMenu mnuTransaksi;
    private javax.swing.JButton txtKepemilikan;
    // End of variables declaration//GEN-END:variables

}
