/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package aplikasi.view.menu.peminjaman;

import static aplikasi.config.AllFieldNotEmpty.areAllNotEmpty;
import static aplikasi.config.AllFieldNotEmpty.areAllNotEmpty;
import aplikasi.config.FieldLimit;
import aplikasi.config.KoneksiDB;
import aplikasi.config.ValueFormatter;
import aplikasi.controller.TableViewController;
import aplikasi.entity.Aset;
import aplikasi.entity.Peminjaman;
import aplikasi.entity.PeminjamanDetail;
import aplikasi.entity.Users;
import aplikasi.repository.RepoPeminjaman;
import aplikasi.service.ServicePeminjaman;
import aplikasi.view.MainMenuView;
import java.awt.event.KeyEvent;
import java.beans.PropertyVetoException;
import java.sql.Date;
import java.sql.SQLException;
import java.time.LocalDate;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import net.sf.jasperreports.engine.JRException;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.engine.data.JRBeanCollectionDataSource;
import net.sf.jasperreports.view.JasperViewer;

/**
 *
 * @author dhiskar
 */
public class DataPeminjamanView extends javax.swing.JInternalFrame {

    private final Peminjaman peminjaman;
    private final MainMenuView menuController;
    private final TableViewController tableController;
    private final RepoPeminjaman repoPeminjaman;
    private final List<PeminjamanDetail> daftarPeminjaman = new ArrayList<>();
    private Users p;

    /**
     * Creates new form DataPenambahanDetailView
     *
     * @param menuController
     */
    public DataPeminjamanView(MainMenuView menuController, Users p) {
        this.menuController = menuController;
        initComponents();
        this.peminjaman = new Peminjaman();
        this.repoPeminjaman = new ServicePeminjaman(KoneksiDB.getDataSource());
        this.tableController = new TableViewController(tableView);
        this.txtTanggal.setDate(new java.util.Date());
        this.p = p;
        textFieldLimit();
        btnCetak.setVisible(false);
        try {
            List<Peminjaman> df = repoPeminjaman.findPeminjamanByTanggal(Date.valueOf(LocalDate.now()));
            StringBuilder kp = new StringBuilder("PMJ").append("-");
            kp.append(ValueFormatter.getLocalDateShortest(LocalDate.now())).append("-");
            kp.append(String.format("%03d", df.size() + 1));
            this.peminjaman.setKode(kp.toString());
            txtKode.setText(this.peminjaman.getKode());
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(this, "Tidak dapat mendapatkan kode peminjaman", getTitle(), JOptionPane.ERROR_MESSAGE);
            Logger.getLogger(DataPeminjamanView.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPopupMenu1 = new javax.swing.JPopupMenu();
        pmnuHapus = new javax.swing.JMenuItem();
        jSeparator2 = new javax.swing.JPopupMenu.Separator();
        pmnuTambah = new javax.swing.JMenuItem();
        jToolBar1 = new javax.swing.JToolBar();
        btnSimpan = new javax.swing.JButton();
        btnCetak = new javax.swing.JButton();
        btnReset = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jToolBar2 = new javax.swing.JToolBar();
        btnTambahAset = new javax.swing.JButton();
        btnHapusAset = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tableView = new javax.swing.JTable();
        txtTotal = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        txtKode = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtTanggal = new com.toedter.calendar.JDateChooser();
        txtNamaPembawa = new javax.swing.JTextField();
        txtKeterangan = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();

        pmnuHapus.setText("Hapus");
        pmnuHapus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pmnuHapusActionPerformed(evt);
            }
        });
        jPopupMenu1.add(pmnuHapus);
        jPopupMenu1.add(jSeparator2);

        pmnuTambah.setText("Tambah");
        pmnuTambah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pmnuTambahActionPerformed(evt);
            }
        });
        jPopupMenu1.add(pmnuTambah);

        setBorder(javax.swing.BorderFactory.createMatteBorder(5, 5, 5, 5, new java.awt.Color(99, 130, 203)));
        setResizable(true);
        setTitle("Peminjaman Aset");

        jToolBar1.setRollover(true);

        btnSimpan.setText("Simpan");
        btnSimpan.setToolTipText("Simpan dan cetak nota");
        btnSimpan.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnSimpan.setMaximumSize(new java.awt.Dimension(120, 35));
        btnSimpan.setMinimumSize(new java.awt.Dimension(120, 35));
        btnSimpan.setPreferredSize(new java.awt.Dimension(120, 35));
        btnSimpan.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnSimpan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSimpanActionPerformed(evt);
            }
        });
        btnSimpan.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                btnSimpanKeyPressed(evt);
            }
        });
        jToolBar1.add(btnSimpan);

        btnCetak.setText("Cetak");
        btnCetak.setFocusable(false);
        btnCetak.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnCetak.setMaximumSize(new java.awt.Dimension(120, 35));
        btnCetak.setMinimumSize(new java.awt.Dimension(120, 35));
        btnCetak.setPreferredSize(new java.awt.Dimension(120, 35));
        btnCetak.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnCetak.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCetakActionPerformed(evt);
            }
        });
        jToolBar1.add(btnCetak);

        btnReset.setText("Reset");
        btnReset.setToolTipText("Form pada kondisi awal");
        btnReset.setFocusable(false);
        btnReset.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnReset.setMaximumSize(new java.awt.Dimension(120, 35));
        btnReset.setMinimumSize(new java.awt.Dimension(120, 35));
        btnReset.setPreferredSize(new java.awt.Dimension(120, 35));
        btnReset.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnReset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnResetActionPerformed(evt);
            }
        });
        jToolBar1.add(btnReset);

        getContentPane().add(jToolBar1, java.awt.BorderLayout.PAGE_END);

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 18))); // NOI18N

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Daftar Dies"));
        jPanel1.setFocusable(false);
        jPanel1.setLayout(new java.awt.BorderLayout());

        jToolBar2.setRollover(true);

        btnTambahAset.setText("Tambah");
        btnTambahAset.setToolTipText("Tambah daftar aset");
        btnTambahAset.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnTambahAset.setMaximumSize(new java.awt.Dimension(120, 35));
        btnTambahAset.setMinimumSize(new java.awt.Dimension(120, 30));
        btnTambahAset.setPreferredSize(new java.awt.Dimension(120, 35));
        btnTambahAset.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnTambahAset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTambahAsetActionPerformed(evt);
            }
        });
        btnTambahAset.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                btnTambahAsetKeyPressed(evt);
            }
        });
        jToolBar2.add(btnTambahAset);

        btnHapusAset.setText("Hapus");
        btnHapusAset.setToolTipText("Hapus daftar aset yang di pilih");
        btnHapusAset.setFocusable(false);
        btnHapusAset.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnHapusAset.setMaximumSize(new java.awt.Dimension(120, 35));
        btnHapusAset.setMinimumSize(new java.awt.Dimension(120, 30));
        btnHapusAset.setPreferredSize(new java.awt.Dimension(120, 35));
        btnHapusAset.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnHapusAset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHapusAsetActionPerformed(evt);
            }
        });
        jToolBar2.add(btnHapusAset);

        jPanel1.add(jToolBar2, java.awt.BorderLayout.PAGE_END);

        jScrollPane1.setFocusable(false);

        tableView.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Kode", "Nama Aset", "Kategori", "Kepemilikan", "Jumlah"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tableView.setFocusable(false);
        tableView.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                tableViewMouseReleased(evt);
            }
        });
        jScrollPane1.setViewportView(tableView);
        if (tableView.getColumnModel().getColumnCount() > 0) {
            tableView.getColumnModel().getColumn(0).setMinWidth(100);
            tableView.getColumnModel().getColumn(0).setPreferredWidth(100);
            tableView.getColumnModel().getColumn(0).setMaxWidth(100);
            tableView.getColumnModel().getColumn(2).setMinWidth(150);
            tableView.getColumnModel().getColumn(2).setPreferredWidth(150);
            tableView.getColumnModel().getColumn(2).setMaxWidth(150);
            tableView.getColumnModel().getColumn(4).setMinWidth(150);
            tableView.getColumnModel().getColumn(4).setPreferredWidth(150);
            tableView.getColumnModel().getColumn(4).setMaxWidth(150);
        }

        txtTotal.setEditable(false);
        txtTotal.setBackground(new java.awt.Color(208, 225, 242));
        txtTotal.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        txtTotal.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtTotal.setFocusable(false);

        jLabel5.setText("Total Peminjaman");
        jLabel5.setFocusable(false);

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 729, Short.MAX_VALUE)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 261, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txtTotal, javax.swing.GroupLayout.DEFAULT_SIZE, 30, Short.MAX_VALUE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        jPanel1.add(jPanel4, java.awt.BorderLayout.CENTER);

        txtKode.setEditable(false);
        txtKode.setToolTipText("Nomor Surat Jalan");
        txtKode.setFocusable(false);

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel1.setText("Kode");

        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel2.setText("Tanggal");

        txtTanggal.setToolTipText("");
        txtTanggal.setFocusable(false);
        txtTanggal.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        txtTanggal.setMinimumSize(new java.awt.Dimension(14, 24));
        txtTanggal.setPreferredSize(new java.awt.Dimension(14, 24));

        txtNamaPembawa.setToolTipText("Yang mengambil dies");

        txtKeterangan.setToolTipText("Dikembalikan ke Customer / Di PRF");

        jLabel3.setText("Nama Pembawa");

        jLabel6.setText("Keterangan");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 745, Short.MAX_VALUE)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtKode, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtTanggal, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel6, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.TRAILING))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txtKeterangan, javax.swing.GroupLayout.DEFAULT_SIZE, 175, Short.MAX_VALUE)
                    .addComponent(txtNamaPembawa))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(13, 13, 13)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(txtNamaPembawa, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(10, 10, 10))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtKode, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel6)
                        .addComponent(txtKeterangan, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(txtTanggal, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 362, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel2, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents
 private void textFieldLimit() {
        txtKode.setDocument(new FieldLimit(20));
        txtNamaPembawa.setDocument(new FieldLimit(30));
        txtKeterangan.setDocument(new FieldLimit(300));
    }
    private void btnSimpanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSimpanActionPerformed
        if (areAllNotEmpty(daftarPeminjaman, txtKode.getText(), txtNamaPembawa.getText())) {
            try {
                this.peminjaman.setKode(txtKode.getText());
                this.peminjaman.setPembawa(txtNamaPembawa.getText());
                this.peminjaman.setTanggal(Date.valueOf(ValueFormatter.getDateSQL(txtTanggal.getDate())));
                this.peminjaman.setKet(txtKeterangan.getText());

                this.peminjaman.setUser(p);
                if (JOptionPane.showConfirmDialog(this, "Data yang telah di simpan tidak dapat di ubah.\nSimpan data ?", getTitle(),
                        JOptionPane.OK_CANCEL_OPTION) == JOptionPane.OK_OPTION) {
                    repoPeminjaman.save(peminjaman, daftarPeminjaman);
                    DataPeminjamanView view = new DataPeminjamanView(menuController, p);
                    this.menuController.setInnerLayout(view);
                    if (JOptionPane.showConfirmDialog(this, "Data berhasil disimpan, Cetak Nota ?", getTitle(),
                            JOptionPane.YES_NO_OPTION) == JOptionPane.YES_OPTION) {
                        btnCetakActionPerformed(evt);
                    }
                } else {
                    //no actiaon
                }
            } catch (SQLException ex) {
                JOptionPane.showMessageDialog(this, "Tidak dapat menyimpan transaksi peminjaman", getTitle(), JOptionPane.ERROR_MESSAGE);
                Logger.getLogger(DataPeminjamanView.class.getName()).log(Level.SEVERE, null, ex);
            } catch (PropertyVetoException ex) {
                Logger.getLogger(DataPeminjamanView.class.getName()).log(Level.SEVERE, null, ex);
            }
        } else {
            JOptionPane.showMessageDialog(this, "Data yang di masukkan belum lengkap !");

        }

    }//GEN-LAST:event_btnSimpanActionPerformed

    private void btnResetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnResetActionPerformed
        try {
            DataPeminjamanView view = new DataPeminjamanView(menuController, p);
            this.menuController.setInnerLayout(view);
        } catch (PropertyVetoException ex) {
            Logger.getLogger(DataPeminjamanView.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnResetActionPerformed

    private void btnHapusAsetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHapusAsetActionPerformed
        if (tableController.isSelected()) {
            PeminjamanDetail pd = daftarPeminjaman.get(tableController.getRowSelected());
            hapusAsetBelanjaan(pd);
        } else {
            JOptionPane.showMessageDialog(this, "Data belanjaan belum dipilih", getTitle(), JOptionPane.WARNING_MESSAGE);
        }
    }//GEN-LAST:event_btnHapusAsetActionPerformed

    private void btnTambahAsetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTambahAsetActionPerformed
        DetailPeminjamanView view = new DetailPeminjamanView(menuController, this, peminjaman, true);
        view.setLocationRelativeTo(null);
        view.setResizable(false);
        view.setVisible(true);
    }//GEN-LAST:event_btnTambahAsetActionPerformed

    private void btnCetakActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCetakActionPerformed
        if (areAllNotEmpty(daftarPeminjaman, txtKode.getText(), txtNamaPembawa.getText())) {
            try {
                String url = "/laporan/NotaPeminjaman.jasper";
                Map<String, Object> map = new HashMap<>();
                map.put("kode", txtKode.getText());
                map.put("tanggal", txtTanggal.getDate());
                map.put("pembawa", txtNamaPembawa.getText());
                map.put("jabatan", p.getJabatan().toString());
                map.put("pengguna", p.getNama());
                map.put("ket", txtKeterangan.getText());
                Integer total = Integer.valueOf(txtTotal.getText());
                map.put("total", total);
                JasperPrint print = JasperFillManager.fillReport(
                        getClass().getResourceAsStream(url),
                        map,
                        new JRBeanCollectionDataSource(daftarPeminjaman));
                JasperViewer view = new JasperViewer(print, false);
                view.setLocationRelativeTo(null);
                view.setExtendedState(JasperViewer.MAXIMIZED_BOTH);
                view.setVisible(true);
            } catch (JRException ex) {
                Logger.getLogger(DataPeminjamanView.class.getName()).log(Level.SEVERE, null, ex);
            }
        } else {
            JOptionPane.showMessageDialog(null, "Data  belum lengkap !");

        }
    }//GEN-LAST:event_btnCetakActionPerformed

    private void tableViewMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tableViewMouseReleased
        if (evt.isPopupTrigger()) {
            JTable source = (JTable) evt.getSource();
            int row = source.rowAtPoint(evt.getPoint());
            int column = source.columnAtPoint(evt.getPoint());
            if (!source.isRowSelected(row)) {
                source.changeSelection(row, column, false, false);
            }
            jPopupMenu1.show(evt.getComponent(), evt.getX(), evt.getY());
        } 
    }//GEN-LAST:event_tableViewMouseReleased

    private void pmnuHapusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pmnuHapusActionPerformed
        btnHapusAsetActionPerformed(evt);
    }//GEN-LAST:event_pmnuHapusActionPerformed

    private void pmnuTambahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pmnuTambahActionPerformed
        btnTambahAsetActionPerformed(evt);
    }//GEN-LAST:event_pmnuTambahActionPerformed

    private void btnTambahAsetKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_btnTambahAsetKeyPressed
        if (evt.getKeyCode()==KeyEvent.VK_ENTER) {
            btnTambahAsetActionPerformed(null);
        }
    }//GEN-LAST:event_btnTambahAsetKeyPressed

    private void btnSimpanKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_btnSimpanKeyPressed
        if (evt.getKeyCode()==KeyEvent.VK_ENTER) {
            btnSimpanActionPerformed(null);
        }
    }//GEN-LAST:event_btnSimpanKeyPressed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCetak;
    private javax.swing.JButton btnHapusAset;
    private javax.swing.JButton btnReset;
    private javax.swing.JButton btnSimpan;
    private javax.swing.JButton btnTambahAset;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPopupMenu jPopupMenu1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JPopupMenu.Separator jSeparator2;
    private javax.swing.JToolBar jToolBar1;
    private javax.swing.JToolBar jToolBar2;
    private javax.swing.JMenuItem pmnuHapus;
    private javax.swing.JMenuItem pmnuTambah;
    private javax.swing.JTable tableView;
    private javax.swing.JTextField txtKeterangan;
    private javax.swing.JTextField txtKode;
    private javax.swing.JTextField txtNamaPembawa;
    private com.toedter.calendar.JDateChooser txtTanggal;
    private javax.swing.JTextField txtTotal;
    // End of variables declaration//GEN-END:variables

    private void refrestDataTable() {
        tableController.clearData();
        int grantTotal = 0;
        for (PeminjamanDetail hapusDetail : daftarPeminjaman) {
            Aset aset = hapusDetail.getAset();
            Object[] row = {
                aset.getKode(),
                aset.getNama(),
                aset.getKategoriAset().getNama_kategori(),
                aset.getKepemilikan().getNama(),
                hapusDetail.getQty(),};
            tableController.getModel().addRow(row);
            grantTotal += hapusDetail.getQty();
        }
        txtTotal.setText(String.valueOf(grantTotal));
        tableController.setContentTableAlignment( Arrays.asList(0, 2, 3, 4));
    }

    void hapusAsetBelanjaan(PeminjamanDetail pd) {
        daftarPeminjaman.remove(pd);
        refrestDataTable();
    }

    void tambahAsetBelanjaan(PeminjamanDetail pd) {
        List<String> kode = new ArrayList<>();
        for (PeminjamanDetail hapusDetail : daftarPeminjaman) {
            Aset aset = hapusDetail.getAset();
            kode.add(aset.getKode());
        }
        if (kode.contains(pd.getAset().getKode())) {
            JOptionPane.showMessageDialog(null, "Kode aset sudah ada !");
        } else {
            daftarPeminjaman.add(pd);
            refrestDataTable();
        }

    }
}
