/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package aplikasi.view.menu.user;

import aplikasi.config.FieldLimit;
import aplikasi.config.FieldMinimal;
import aplikasi.config.KoneksiDB;
import aplikasi.entity.Users;
import aplikasi.repository.RepoUsers;
import aplikasi.service.ServiceUsers;
import java.awt.event.ItemEvent;
import java.awt.event.KeyEvent;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author dhiskar
 */
public class DataUserView extends javax.swing.JDialog {

    private List<Users> daftarUsers = new ArrayList<>();
    private DaftarUserView daftarLokasiViewController;
    private Boolean update;
    private final Users pengguna;
    private final RepoUsers repoUsers = new ServiceUsers(KoneksiDB.getDataSource());
    private final FieldMinimal jTextFieldMinimal;

    public Boolean isUpdate() {
        return update;
    }

    public void setUpdate(Boolean update) {
        this.update = update;
    }

    public DataUserView(java.awt.Frame parent, boolean b) {
        super(parent, b);
        initComponents();
        setUpdate(false);
        this.daftarLokasiViewController = null;
        this.pengguna = new Users();
        this.jTextFieldMinimal = new FieldMinimal();
        ambilIdTerbesar();
        textFieldLimit();
        txtNama.requestFocus();
    }

    public DataUserView(java.awt.Frame parent, DaftarUserView daftarLokasiViewController, boolean b) {
        super(parent, b);
        initComponents();
        setUpdate(false);
        this.daftarLokasiViewController = daftarLokasiViewController;
        this.pengguna = new Users();
        this.jTextFieldMinimal = new FieldMinimal();
        ambilIdTerbesar();
        textFieldLimit();
        txtNama.requestFocus();
    }

    public DataUserView(java.awt.Frame parent, DaftarUserView daftarLokasiViewController, Users pengguna, boolean b) {
        super(parent, b);
        initComponents();
        setUpdate(true);
        this.daftarLokasiViewController = daftarLokasiViewController;
        this.pengguna = new Users();
        this.jTextFieldMinimal = new FieldMinimal();
        textFieldLimit();
        setFilds(pengguna);
        txtNama.requestFocus();
    }

    private void textFieldLimit() {
        txtNama.setDocument(new FieldLimit(30));
        txtUsername.setDocument(new FieldLimit(8));
        txtPassword.setDocument(new FieldLimit(8));
    }

    private void clearFields() {
        txtKode.setText("");
        txtNama.setText("");
        txtUsername.setText("");
        txtPassword.setText("");
        txtJabatan.setSelectedIndex(1);
        txtStatus.setSelectedIndex(1);
    }

    private void setFilds(Users pengguna) {
        txtKode.setText(pengguna.getId_user().toString());
        txtNama.setText(pengguna.getNama());
        txtUsername.setText(pengguna.getUsername());
        txtPassword.setText(pengguna.getPassword());
        txtJabatan.setSelectedItem(pengguna.getJabatan().toString());
        if (pengguna.getStatus()) {
            txtStatus.setSelectedIndex(0);
        } else {
            txtStatus.setSelectedIndex(1);
        }
    }

    private void ambilIdTerbesar() {
        try {
            daftarUsers = repoUsers.findMaxValue();
            if (daftarUsers.size() != 0) {
                for (Users p : daftarUsers) {
                    int i = p.getId_user() + 1;
                    txtKode.setText(String.valueOf(i));
                }
            } else {
                txtKode.setText("1");
            }

        } catch (Exception e) {
            Logger.getLogger(DataUserView.class.getName()).log(Level.SEVERE, null, e);

        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jToolBar1 = new javax.swing.JToolBar();
        btnSimpan = new javax.swing.JButton();
        btnKembali = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        txtKode = new javax.swing.JTextField();
        txtNama = new javax.swing.JTextField("Input Nama", 30);
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txtUsername = new javax.swing.JTextField();
        txtPassword = new javax.swing.JPasswordField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txtJabatan = new javax.swing.JComboBox<String>();
        cboHidePassword = new javax.swing.JCheckBox();
        txtStatus = new javax.swing.JComboBox<String>();
        jLabel6 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("User");
        setIconImage(new javax.swing.ImageIcon(getClass().getResource("/gambar/logo3.png")).getImage());

        jToolBar1.setRollover(true);
        jToolBar1.setMaximumSize(new java.awt.Dimension(18, 39));
        jToolBar1.setPreferredSize(new java.awt.Dimension(18, 39));

        btnSimpan.setText("Simpan");
        btnSimpan.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btnSimpan.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnSimpan.setMaximumSize(new java.awt.Dimension(120, 35));
        btnSimpan.setMinimumSize(new java.awt.Dimension(120, 35));
        btnSimpan.setPreferredSize(new java.awt.Dimension(120, 35));
        btnSimpan.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnSimpan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSimpanActionPerformed(evt);
            }
        });
        btnSimpan.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                btnSimpanKeyReleased(evt);
            }
        });
        jToolBar1.add(btnSimpan);

        btnKembali.setText("Kembali");
        btnKembali.setFocusable(false);
        btnKembali.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnKembali.setMaximumSize(new java.awt.Dimension(120, 35));
        btnKembali.setMinimumSize(new java.awt.Dimension(120, 35));
        btnKembali.setPreferredSize(new java.awt.Dimension(120, 35));
        btnKembali.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnKembali.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnKembaliActionPerformed(evt);
            }
        });
        jToolBar1.add(btnKembali);

        getContentPane().add(jToolBar1, java.awt.BorderLayout.PAGE_END);

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Data User"));

        jLabel1.setText("Kode");

        txtKode.setEditable(false);
        txtKode.setFocusable(false);

        txtNama.setToolTipText("Nama minimal 2 karakter, maximal 30 karakter dan hanya huruf");
        txtNama.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtNamaFocusLost(evt);
            }
        });
        txtNama.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtNamaKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtNamaKeyTyped(evt);
            }
        });

        jLabel2.setText("Nama User");

        jLabel3.setText("Username");

        txtUsername.setToolTipText("Username minimal 4 karakter dan maximal 8 karakter");

        txtPassword.setToolTipText("Password minimal 4 karakter, mengandung huruh besar, kecil dan angka");

        jLabel4.setText("Password");

        jLabel5.setText("Jabatan");

        txtJabatan.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Admin", "Gudang", "Kasir", "Kepala" }));

        cboHidePassword.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        cboHidePassword.setText("Show password");
        cboHidePassword.setFocusable(false);
        cboHidePassword.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cboHidePasswordItemStateChanged(evt);
            }
        });

        txtStatus.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Aktif", "Tidak Aktif" }));

        jLabel6.setText("Status");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtKode, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtNama, javax.swing.GroupLayout.PREFERRED_SIZE, 217, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtUsername, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtJabatan, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(txtPassword, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cboHidePassword))
                    .addComponent(txtStatus, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(63, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtKode, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txtNama, javax.swing.GroupLayout.DEFAULT_SIZE, 30, Short.MAX_VALUE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtUsername, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(cboHidePassword, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(txtPassword, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtJabatan, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtStatus, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(17, 17, 17))
        );

        getContentPane().add(jPanel1, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnSimpanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSimpanActionPerformed
        if ((!jTextFieldMinimal.setMinInputValue(txtNama.getText(), 2) || !jTextFieldMinimal.setOnlyLetter(txtNama.getText()))) {
            JOptionPane.showMessageDialog(this, "Nama minimal 2 karakter dan hanya huruf !");
            txtNama.requestFocus();
            txtNama.selectAll();
        } else if (!jTextFieldMinimal.setMinInputValue(txtUsername.getText(), 4)) {
            JOptionPane.showMessageDialog(this, "Username minimal 4 karakter !");
            txtUsername.requestFocus();
            txtUsername.selectAll();
        } else if (!jTextFieldMinimal.setMinInputValue(txtPassword.getText())) {
            JOptionPane.showMessageDialog(this, "Password minimal 4 karakter, mengandung huruh besar, kecil dan angka !");
            txtPassword.requestFocus();
            txtPassword.selectAll();
        } else {
            pengguna.setId_user(Integer.valueOf(txtKode.getText()));
            pengguna.setNama(txtNama.getText());
            pengguna.setUsername(txtUsername.getText());
            pengguna.setPassword(txtPassword.getText());
            pengguna.setJabatan(Users.Role.valueOf(txtJabatan.getSelectedItem().toString()));
            if (txtStatus.getSelectedItem().equals("Aktif")) {
                pengguna.setStatus(true);
            } else {
                pengguna.setStatus(false);
            }

            if (isUpdate()) {
                try {
                    repoUsers.update(pengguna);
                    this.dispose();
                    if (daftarLokasiViewController != null) {
                        daftarLokasiViewController.refreshDataTableByName();
                        daftarLokasiViewController.setFields(pengguna);

                    }
                } catch (SQLException ex) {
                    JOptionPane.showMessageDialog(this, "Username harus unique !", getTitle(), JOptionPane.ERROR_MESSAGE);
                    Logger.getLogger(DataUserView.class.getName()).log(Level.SEVERE, null, ex);
                }
            } else {
                try {
                    repoUsers.save(pengguna);
                    this.dispose();
                    if (daftarLokasiViewController != null) {
                        daftarLokasiViewController.refreshDataTableByName();
                        daftarLokasiViewController.setFields(pengguna);
                        daftarLokasiViewController.selectLastRow();
                        daftarLokasiViewController.btnTambahRequestFocus();
                    }
                } catch (SQLException ex) {
                    JOptionPane.showMessageDialog(this, "Username harus unique !", getTitle(), JOptionPane.ERROR_MESSAGE);
                    //                    JOptionPane.showMessageDialog(this, ex, getTitle(), JOptionPane.ERROR_MESSAGE);
                    Logger.getLogger(DataUserView.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        }
    }//GEN-LAST:event_btnSimpanActionPerformed

    private void btnKembaliActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnKembaliActionPerformed
        this.dispose();
    }//GEN-LAST:event_btnKembaliActionPerformed

    private void txtNamaFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtNamaFocusLost

    }//GEN-LAST:event_txtNamaFocusLost

    private void txtNamaKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtNamaKeyReleased

    }//GEN-LAST:event_txtNamaKeyReleased

    private void txtNamaKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtNamaKeyTyped

    }//GEN-LAST:event_txtNamaKeyTyped

    private void cboHidePasswordItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cboHidePasswordItemStateChanged
        if (evt.getStateChange() == ItemEvent.SELECTED) {
            txtPassword.setEchoChar((char) 0);
        } else {
            txtPassword.setEchoChar('•');
        }
    }//GEN-LAST:event_cboHidePasswordItemStateChanged

    private void btnSimpanKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_btnSimpanKeyReleased
        if (evt.getKeyCode()== KeyEvent.VK_ENTER) {
            btnSimpanActionPerformed(null);
        }
    }//GEN-LAST:event_btnSimpanKeyReleased

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnKembali;
    private javax.swing.JButton btnSimpan;
    private javax.swing.JCheckBox cboHidePassword;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JToolBar jToolBar1;
    private javax.swing.JComboBox<String> txtJabatan;
    private javax.swing.JTextField txtKode;
    private javax.swing.JTextField txtNama;
    private javax.swing.JPasswordField txtPassword;
    private javax.swing.JComboBox<String> txtStatus;
    private javax.swing.JTextField txtUsername;
    // End of variables declaration//GEN-END:variables
}
