/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package aplikasi.view.menu.kepemilikan;

import aplikasi.config.FieldLimit;
import aplikasi.config.FieldMinimal;
import aplikasi.config.KoneksiDB;
import aplikasi.entity.Kepemilikan;
import aplikasi.repository.RepoKepemilikan;
import aplikasi.service.ServiceKepemilikan;
import java.awt.event.KeyEvent;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author dhiskar
 */
public class DataKepemilikanView extends javax.swing.JDialog {

    private List<Kepemilikan> daftarPelanggan = new ArrayList<>();
    private DaftarKepemilikanView daftarPelangganViewController;
    private Boolean update;
    private final Kepemilikan kepemilikan;
    private final RepoKepemilikan repoPelanggan = new ServiceKepemilikan(KoneksiDB.getDataSource());
    private FieldMinimal jTextFieldMinimal;

    public Boolean isUpdate() {
        return update;
    }

    public void setUpdate(Boolean update) {
        this.update = update;
    }

    public DataKepemilikanView(java.awt.Frame parent, boolean b) {
        super(parent, b);
        initComponents();
        setUpdate(false);
        this.kepemilikan = new Kepemilikan();
        this.jTextFieldMinimal = new FieldMinimal();
        this.daftarPelangganViewController = null;
        ambilIdTerbesar();
        textFieldLimit();
        txtNama.requestFocus();
    }

    DataKepemilikanView(java.awt.Frame parent, DaftarKepemilikanView daftarPelangganViewController, boolean b) {
        super(parent, b);
        initComponents();
        setUpdate(false);
        this.daftarPelangganViewController = daftarPelangganViewController;
        this.kepemilikan = new Kepemilikan();
        this.jTextFieldMinimal = new FieldMinimal();
        ambilIdTerbesar();
        textFieldLimit();
        txtNama.requestFocus();
    }

    DataKepemilikanView(java.awt.Frame parent, DaftarKepemilikanView daftarPelangganViewController, Kepemilikan kepemilikan, boolean b) {
        super(parent, b);
        initComponents();
        textFieldLimit();
        this.daftarPelangganViewController = daftarPelangganViewController;
        setUpdate(true);
        this.kepemilikan = new Kepemilikan();
        this.jTextFieldMinimal = new FieldMinimal();
        setFilds(kepemilikan);
        txtNama.requestFocus();
    }

    private void textFieldLimit() {
        txtNama.setDocument(new FieldLimit(40));
        txtTlp.setDocument(new FieldLimit(12));
        txtAlamat.setDocument(new FieldLimit(300));
        txtKet.setDocument(new FieldLimit(300));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jToolBar1 = new javax.swing.JToolBar();
        btnSimpan = new javax.swing.JButton();
        btnKembali = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txtKode = new javax.swing.JTextField();
        txtNama = new javax.swing.JTextField();
        txtTlp = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtAlamat = new javax.swing.JTextArea();
        jScrollPane2 = new javax.swing.JScrollPane();
        txtKet = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Kepemilikan");
        setIconImage(new javax.swing.ImageIcon(getClass().getResource("/gambar/logo3.png")).getImage());

        jToolBar1.setRollover(true);

        btnSimpan.setText("Simpan");
        btnSimpan.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnSimpan.setMaximumSize(new java.awt.Dimension(120, 35));
        btnSimpan.setMinimumSize(new java.awt.Dimension(120, 35));
        btnSimpan.setPreferredSize(new java.awt.Dimension(120, 35));
        btnSimpan.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnSimpan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSimpanActionPerformed(evt);
            }
        });
        btnSimpan.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                btnSimpanKeyReleased(evt);
            }
        });
        jToolBar1.add(btnSimpan);

        btnKembali.setText("Kembali");
        btnKembali.setFocusable(false);
        btnKembali.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnKembali.setMaximumSize(new java.awt.Dimension(120, 35));
        btnKembali.setMinimumSize(new java.awt.Dimension(120, 35));
        btnKembali.setPreferredSize(new java.awt.Dimension(120, 35));
        btnKembali.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnKembali.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnKembaliActionPerformed(evt);
            }
        });
        jToolBar1.add(btnKembali);

        getContentPane().add(jToolBar1, java.awt.BorderLayout.PAGE_END);

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Data Kepemilkan Aset"));

        jLabel1.setText("Kode");

        jLabel2.setText("Nama");

        jLabel3.setText("Telepon");

        txtKode.setEditable(false);
        txtKode.setFocusable(false);

        txtNama.setToolTipText("Nama minimal 4 karakter, maximal 40 karakter dan hanya huruf");
        txtNama.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtNamaKeyTyped(evt);
            }
        });

        txtTlp.setToolTipText("Telepon minimal 6 karakter, maximal 12 karakter dan hanya huruf");
        txtTlp.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtTlpKeyTyped(evt);
            }
        });

        jLabel15.setText("Alamat");

        jLabel16.setText("Keterangan");

        txtAlamat.setColumns(20);
        txtAlamat.setLineWrap(true);
        txtAlamat.setRows(5);
        txtAlamat.setToolTipText("Nama minimal 4 karakter, maximal 300 karakter");
        txtAlamat.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtAlamatKeyPressed(evt);
            }
        });
        jScrollPane1.setViewportView(txtAlamat);

        txtKet.setColumns(20);
        txtKet.setLineWrap(true);
        txtKet.setRows(5);
        txtKet.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtKetKeyPressed(evt);
            }
        });
        jScrollPane2.setViewportView(txtKet);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel15, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, 52, Short.MAX_VALUE)
                            .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtKode, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtTlp, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 69, Short.MAX_VALUE))
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addComponent(txtNama))
                .addGap(188, 188, 188))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txtKode, javax.swing.GroupLayout.DEFAULT_SIZE, 30, Short.MAX_VALUE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txtNama, javax.swing.GroupLayout.DEFAULT_SIZE, 30, Short.MAX_VALUE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txtTlp, javax.swing.GroupLayout.DEFAULT_SIZE, 30, Short.MAX_VALUE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(25, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel1, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents
    private void ambilIdTerbesar() {
        try {
            daftarPelanggan = repoPelanggan.findMaxValue();
            if (daftarPelanggan.size() != 0) {
                for (Kepemilikan p : daftarPelanggan) {
                    int i = p.getId_kepemilikan() + 1;
                    txtKode.setText(String.valueOf(i));
                }
            } else {
                txtKode.setText("1");
            }

        } catch (Exception e) {
            Logger.getLogger(DataKepemilikanView.class.getName()).log(Level.SEVERE, null, e);

        }
    }
    private void btnSimpanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSimpanActionPerformed
        if (!jTextFieldMinimal.setMinInputValue(txtNama.getText(), 4)|| !jTextFieldMinimal.setOnlyLetter(txtNama.getText())) {
            JOptionPane.showMessageDialog(this, "Nama minimal 4 karakter dan hanya huruf !");
            txtNama.requestFocus();
            txtNama.selectAll();
        } else if (!jTextFieldMinimal.setMinInputValue(txtTlp.getText(), 6)) {
            JOptionPane.showMessageDialog(this, "Telepon minimal 6 karakter !");
            txtTlp.requestFocus();
            txtTlp.selectAll();
        } else if (!jTextFieldMinimal.setMinInputValue(txtAlamat.getText(),4)) {
            JOptionPane.showMessageDialog(this, "Alamat minimal 4 karakter !");
            txtAlamat.requestFocus();
            txtAlamat.selectAll();
        } else {
            kepemilikan.setId_kepemilikan(Integer.valueOf(txtKode.getText()));
            kepemilikan.setNama(txtNama.getText());
            kepemilikan.setTlp(txtTlp.getText());
            kepemilikan.setAlamat(txtAlamat.getText());
            kepemilikan.setKet(txtKet.getText());

            if (isUpdate()) {
                try {
                    repoPelanggan.update(kepemilikan);
                    this.dispose();
                    if (daftarPelangganViewController != null) {
                        daftarPelangganViewController.refreshDataTableByName();
                        daftarPelangganViewController.setFields(kepemilikan);
                    }
                } catch (SQLException ex) {
                    JOptionPane.showMessageDialog(this, "Tidak dapat merubah data kepemilikan", getTitle(), JOptionPane.ERROR_MESSAGE);
                    Logger.getLogger(DataKepemilikanView.class.getName()).log(Level.SEVERE, null, ex);
                }
            } else {
                try {
                    repoPelanggan.save(kepemilikan);
                    this.dispose();
                    if (daftarPelangganViewController != null) {
                        daftarPelangganViewController.refreshDataTableByName();
                        daftarPelangganViewController.setFields(kepemilikan);
                        daftarPelangganViewController.selectLastRow();

                    }
                } catch (SQLException ex) {
                    JOptionPane.showMessageDialog(this, "Tidak dapat menyimpan data kepemilikan", getTitle(), JOptionPane.ERROR_MESSAGE);
                    Logger.getLogger(DataKepemilikanView.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        }
    }//GEN-LAST:event_btnSimpanActionPerformed

    private void btnKembaliActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnKembaliActionPerformed
        this.dispose();
    }//GEN-LAST:event_btnKembaliActionPerformed

    private void txtTlpKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtTlpKeyTyped
        FieldLimit.filterhuruf(evt);
    }//GEN-LAST:event_txtTlpKeyTyped

    private void txtNamaKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtNamaKeyTyped
        FieldLimit.filterangka(evt);
    }//GEN-LAST:event_txtNamaKeyTyped

    private void btnSimpanKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_btnSimpanKeyReleased
        if (evt.getKeyCode()==KeyEvent.VK_ENTER) {
            btnSimpanActionPerformed(null);
        }
    }//GEN-LAST:event_btnSimpanKeyReleased

    private void txtAlamatKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtAlamatKeyPressed
         if (evt.getKeyCode()==KeyEvent.VK_TAB) {
            txtKet.requestFocus();
        }
    }//GEN-LAST:event_txtAlamatKeyPressed

    private void txtKetKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtKetKeyPressed
          if (evt.getKeyCode()==KeyEvent.VK_TAB) {
            btnSimpan.requestFocus();
        }
    }//GEN-LAST:event_txtKetKeyPressed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnKembali;
    private javax.swing.JButton btnSimpan;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JToolBar jToolBar1;
    private javax.swing.JTextArea txtAlamat;
    private javax.swing.JTextArea txtKet;
    private javax.swing.JTextField txtKode;
    private javax.swing.JTextField txtNama;
    private javax.swing.JTextField txtTlp;
    // End of variables declaration//GEN-END:variables

    private void clearFields() {
        txtKode.setText("");
        txtNama.setText("");
        txtTlp.setText("");
        txtAlamat.setText("");
        txtKet.setText("");
    }

    private void setFilds(Kepemilikan p) {
        txtKode.setText(p.getId_kepemilikan().toString());
        txtNama.setText(p.getNama());
        txtTlp.setText(p.getTlp());
        txtAlamat.setText(p.getAlamat());
        txtKet.setText(p.getKet());
    }

}
