/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package aplikasi.view.menu.laporan;

import aplikasi.config.KoneksiDB;
import aplikasi.config.ValueFormatter;
import aplikasi.controller.TableViewController;
import aplikasi.entity.Aset;
import aplikasi.entity.PeminjamanDetail;
import aplikasi.entity.PengembalianDetail;
import aplikasi.repository.RepoPeminjaman;
import aplikasi.repository.RepoPengembalian;
import aplikasi.service.ServicePeminjaman;
import aplikasi.service.ServicePengembalian;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author soraya
 */
public final class LaporanLihatTransaksi extends javax.swing.JDialog {
    private final Aset aset;
    private final TableViewController tableControllerPenambahan;
    private final TableViewController tableControllerPenghapusan;
    private final TableViewController tableControllerPeminjaman;
    private final TableViewController tableControllerPengembalian;

    private final RepoPeminjaman repoPeminjaman = new ServicePeminjaman(KoneksiDB.getDataSource());
    private List<PeminjamanDetail> daftarPeminjamanDetail = new ArrayList<>();
    
    private final RepoPengembalian repoPengembalian = new ServicePengembalian(KoneksiDB.getDataSource());
    private List<PengembalianDetail> daftarPengembalianDetail = new ArrayList<>();


    /**
     * Creates new form LaporanLihatTransaksi
     */
    public LaporanLihatTransaksi(java.awt.Frame parent, Aset aset, boolean modal) {
        super(parent, modal);
        initComponents();
        this.aset = aset;
        setFields(aset);
        this.tableControllerPenambahan = new TableViewController(tableVIewPenambahan);
        this.tableControllerPenambahan.setContentTableAlignment(Arrays.asList(0,1,2));
        this.tableControllerPenghapusan = new TableViewController(tableViewPenghapusan);
        this.tableControllerPenghapusan.setContentTableAlignment(Arrays.asList(0,1,2));
        this.tableControllerPeminjaman = new TableViewController(tableViewPeminjaman);
        this.tableControllerPeminjaman.setContentTableAlignment(Arrays.asList(0,1,2));
        this.tableControllerPengembalian = new TableViewController(tableViewPengembalian);
        this.tableControllerPengembalian.setContentTableAlignment(Arrays.asList(0,1,2));
        refreshDataTablesPeminjaman();
        refreshDataTablesPengembalian();
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jToolBar1 = new javax.swing.JToolBar();
        jLabel1 = new javax.swing.JLabel();
        txtKode = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtNama = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txtKategori = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txtStatus = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txtRak = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        txtQty = new javax.swing.JLabel();
        txtSatuan = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        txtKepemilikan = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tableVIewPenambahan = new javax.swing.JTable();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tableViewPenghapusan = new javax.swing.JTable();
        jPanel4 = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        tableViewPeminjaman = new javax.swing.JTable();
        jPanel5 = new javax.swing.JPanel();
        jScrollPane4 = new javax.swing.JScrollPane();
        tableViewPengembalian = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setIconImage(new javax.swing.ImageIcon(getClass().getResource("/gambar/logo3.png")).getImage());
        setMaximumSize(new java.awt.Dimension(1239, 684));
        setMinimumSize(new java.awt.Dimension(1239, 684));
        setPreferredSize(new java.awt.Dimension(1239, 684));
        setResizable(false);

        jToolBar1.setBorder(null);
        jToolBar1.setRollover(true);
        jToolBar1.setMaximumSize(new java.awt.Dimension(13, 35));
        jToolBar1.setMinimumSize(new java.awt.Dimension(13, 35));
        jToolBar1.setPreferredSize(new java.awt.Dimension(100, 35));

        jLabel1.setText(" Kode : ");
        jToolBar1.add(jLabel1);

        txtKode.setForeground(new java.awt.Color(38, 75, 135));
        txtKode.setText("jLabel2");
        jToolBar1.add(txtKode);

        jLabel2.setText("      Nama Aset : ");
        jToolBar1.add(jLabel2);

        txtNama.setForeground(new java.awt.Color(38, 75, 135));
        txtNama.setText("jLabel3");
        jToolBar1.add(txtNama);

        jLabel3.setText("      Kategori : ");
        jToolBar1.add(jLabel3);

        txtKategori.setForeground(new java.awt.Color(38, 75, 135));
        txtKategori.setText("jLabel4");
        jToolBar1.add(txtKategori);

        jLabel4.setText("      Status : ");
        jToolBar1.add(jLabel4);

        txtStatus.setForeground(new java.awt.Color(38, 75, 135));
        txtStatus.setText("jLabel5");
        jToolBar1.add(txtStatus);

        jLabel5.setText("      Rak : ");
        jToolBar1.add(jLabel5);

        txtRak.setForeground(new java.awt.Color(38, 75, 135));
        txtRak.setText("jLabel6");
        jToolBar1.add(txtRak);

        jLabel6.setText("      Qty : ");
        jToolBar1.add(jLabel6);

        txtQty.setForeground(new java.awt.Color(0, 0, 255));
        txtQty.setText("jLabel7");
        jToolBar1.add(txtQty);

        txtSatuan.setForeground(new java.awt.Color(38, 75, 135));
        txtSatuan.setText("jLabel7");
        jToolBar1.add(txtSatuan);

        jLabel7.setText("      Kepemilikan : ");
        jToolBar1.add(jLabel7);

        txtKepemilikan.setForeground(new java.awt.Color(38, 75, 135));
        txtKepemilikan.setText("jLabel8");
        jToolBar1.add(txtKepemilikan);

        getContentPane().add(jToolBar1, java.awt.BorderLayout.PAGE_START);

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder("Penambahan Aset"));

        tableVIewPenambahan.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Kode", "Tanggal", "Ket"
            }
        ));
        jScrollPane1.setViewportView(tableVIewPenambahan);
        if (tableVIewPenambahan.getColumnModel().getColumnCount() > 0) {
            tableVIewPenambahan.getColumnModel().getColumn(0).setMinWidth(0);
            tableVIewPenambahan.getColumnModel().getColumn(0).setPreferredWidth(0);
            tableVIewPenambahan.getColumnModel().getColumn(0).setMaxWidth(0);
            tableVIewPenambahan.getColumnModel().getColumn(1).setMinWidth(75);
            tableVIewPenambahan.getColumnModel().getColumn(1).setPreferredWidth(75);
            tableVIewPenambahan.getColumnModel().getColumn(1).setMaxWidth(75);
        }

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 294, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1)
        );

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder("Penghapusan Aset"));
        jPanel3.setPreferredSize(new java.awt.Dimension(304, 426));

        tableViewPenghapusan.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Kode", "Tanggal", "Ket"
            }
        ));
        jScrollPane2.setViewportView(tableViewPenghapusan);
        if (tableViewPenghapusan.getColumnModel().getColumnCount() > 0) {
            tableViewPenghapusan.getColumnModel().getColumn(0).setMinWidth(0);
            tableViewPenghapusan.getColumnModel().getColumn(0).setPreferredWidth(0);
            tableViewPenghapusan.getColumnModel().getColumn(0).setMaxWidth(0);
            tableViewPenghapusan.getColumnModel().getColumn(1).setMinWidth(75);
            tableViewPenghapusan.getColumnModel().getColumn(1).setPreferredWidth(75);
            tableViewPenghapusan.getColumnModel().getColumn(1).setMaxWidth(75);
        }

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 288, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 626, Short.MAX_VALUE)
        );

        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder("Peminjaman Aset"));
        jPanel4.setPreferredSize(new java.awt.Dimension(304, 426));

        tableViewPeminjaman.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Kode", "Tanggal", "Ket"
            }
        ));
        jScrollPane3.setViewportView(tableViewPeminjaman);
        if (tableViewPeminjaman.getColumnModel().getColumnCount() > 0) {
            tableViewPeminjaman.getColumnModel().getColumn(0).setMinWidth(0);
            tableViewPeminjaman.getColumnModel().getColumn(0).setPreferredWidth(0);
            tableViewPeminjaman.getColumnModel().getColumn(0).setMaxWidth(0);
            tableViewPeminjaman.getColumnModel().getColumn(1).setMinWidth(75);
            tableViewPeminjaman.getColumnModel().getColumn(1).setPreferredWidth(75);
            tableViewPeminjaman.getColumnModel().getColumn(1).setMaxWidth(75);
        }

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 288, Short.MAX_VALUE)
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane3)
        );

        jPanel5.setBorder(javax.swing.BorderFactory.createTitledBorder("Pengembalian Pinjaman Aset"));
        jPanel5.setMaximumSize(new java.awt.Dimension(304, 426));
        jPanel5.setMinimumSize(new java.awt.Dimension(304, 426));
        jPanel5.setPreferredSize(new java.awt.Dimension(304, 426));

        tableViewPengembalian.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Kode", "Tanggal", "Ket"
            }
        ));
        jScrollPane4.setViewportView(tableViewPengembalian);
        if (tableViewPengembalian.getColumnModel().getColumnCount() > 0) {
            tableViewPengembalian.getColumnModel().getColumn(0).setMinWidth(0);
            tableViewPengembalian.getColumnModel().getColumn(0).setPreferredWidth(0);
            tableViewPengembalian.getColumnModel().getColumn(0).setMaxWidth(0);
            tableViewPengembalian.getColumnModel().getColumn(1).setMinWidth(75);
            tableViewPengembalian.getColumnModel().getColumn(1).setPreferredWidth(75);
            tableViewPengembalian.getColumnModel().getColumn(1).setMaxWidth(75);
        }

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane4, javax.swing.GroupLayout.DEFAULT_SIZE, 288, Short.MAX_VALUE)
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane4)
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 649, Short.MAX_VALUE)
            .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, 649, Short.MAX_VALUE)
            .addComponent(jPanel5, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 649, Short.MAX_VALUE)
        );

        getContentPane().add(jPanel1, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JToolBar jToolBar1;
    private javax.swing.JTable tableVIewPenambahan;
    private javax.swing.JTable tableViewPeminjaman;
    private javax.swing.JTable tableViewPengembalian;
    private javax.swing.JTable tableViewPenghapusan;
    private javax.swing.JLabel txtKategori;
    private javax.swing.JLabel txtKepemilikan;
    private javax.swing.JLabel txtKode;
    private javax.swing.JLabel txtNama;
    private javax.swing.JLabel txtQty;
    private javax.swing.JLabel txtRak;
    private javax.swing.JLabel txtSatuan;
    private javax.swing.JLabel txtStatus;
    // End of variables declaration//GEN-END:variables

    private void setFields(Aset aset) {
        txtKode.setText(aset.getKode());
        txtNama.setText(aset.getNama());
        txtKategori.setText(aset.getKategoriAset().getNama_kategori());
        txtStatus.setText(aset.getStatusAset().getStatus());
        txtRak.setText(aset.getLokasiAset().getNama_rak());
        txtQty.setText(aset.getQty().toString());
        txtSatuan.setText(aset.getSatuan());
        txtKepemilikan.setText(aset.getKepemilikan().getNama());
    }
    public void refreshDataTablesPeminjaman() {
        try {
            tableControllerPeminjaman.clearData();
            this.daftarPeminjamanDetail = repoPeminjaman.findPeminjamanDetailByIdAset(aset.getKode());
            for (PeminjamanDetail pd : daftarPeminjamanDetail) {
                Object[] row = {pd.getPeminjaman().getKode(),ValueFormatter.getLocalDateShort( pd.getPeminjaman().getTanggal().toLocalDate()), 
                    pd.getPeminjaman().getKet()};
                tableControllerPeminjaman.getModel().addRow(row);
            }
        } catch (SQLException ex) {
            Logger.getLogger(LaporanAset.class.getName()).log(Level.SEVERE, null, ex);
        }
        
    }
    public void refreshDataTablesPengembalian() {
        try {
            tableControllerPengembalian.clearData();
            this.daftarPengembalianDetail = repoPengembalian.findPengembalianDetailByIdAset(aset.getKode());
            for (PengembalianDetail pd : daftarPengembalianDetail) {
                Object[] row = {pd.getPengembalian().getKode(),ValueFormatter.getLocalDateShort(pd.getPengembalian().getTanggal().toLocalDate()),pd.getPengembalian().getKet()};
                tableControllerPengembalian.getModel().addRow(row);
            }
        } catch (SQLException ex) {
            Logger.getLogger(LaporanAset.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
}
