/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package aplikasi.view.menu.laporan;

import aplikasi.config.KoneksiDB;
import aplikasi.config.ValueFormatter;
import aplikasi.controller.TableViewController;
import aplikasi.entity.KategoriAset;
import aplikasi.entity.Kepemilikan;
import aplikasi.entity.PeminjamanDetail;
import aplikasi.entity.Users;
import aplikasi.repository.RepoKategoriAset;
import aplikasi.repository.RepoKepemilikan;
import aplikasi.repository.RepoPeminjaman;
import aplikasi.service.ServiceKategoriAset;
import aplikasi.service.ServiceKepemilikan;
import aplikasi.service.ServicePeminjaman;
import aplikasi.view.MainMenuView;
import aplikasi.view.menu.aset.DataAsetView;
import java.sql.Date;
import java.sql.SQLException;
import java.time.LocalDate;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import net.sf.jasperreports.engine.JRException;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.engine.data.JRBeanCollectionDataSource;
import net.sf.jasperreports.view.JasperViewer;

/**
 *
 * @author laptop
 */
public final class LaporanPeminjaman extends javax.swing.JInternalFrame {

    private final MainMenuView mainMenuController;
    private final TableViewController tableController;
    private Users p;

    private final RepoKategoriAset repoKategori = new ServiceKategoriAset(KoneksiDB.getDataSource());
    private final RepoKepemilikan repoKepemilikan = new ServiceKepemilikan(KoneksiDB.getDataSource());
    private final RepoPeminjaman repoPeminjaman = new ServicePeminjaman(KoneksiDB.getDataSource());

    private List<KategoriAset> daftarKategori = new ArrayList<>();
    private List<Kepemilikan> daftarKepemilikan = new ArrayList<>();
    private List<PeminjamanDetail> daftarPeminjamanDetail = new ArrayList<>();

    /**
     * Creates new form LaporanPeminjaman
     *
     * @param mainMenuController
     */
    public LaporanPeminjaman(MainMenuView mainMenuController, Users p) {
        initComponents();
        this.mainMenuController = mainMenuController;
        this.tableController = new TableViewController(tableView);
        this.p = p;
        hideFilter();
        refresDataKategoriAset();
        refresDataKepemilikan();
        txtTanggalAwal.setDate(new java.util.Date());
        txtTanggalAkhir.setDate(new java.util.Date());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jToolBar1 = new javax.swing.JToolBar();
        jLabel1 = new javax.swing.JLabel();
        txtTanggalAwal = new com.toedter.calendar.JDateChooser();
        jLabel2 = new javax.swing.JLabel();
        txtTanggalAkhir = new com.toedter.calendar.JDateChooser();
        jSeparator1 = new javax.swing.JToolBar.Separator();
        btnFilter = new javax.swing.JButton();
        lblKategori = new javax.swing.JLabel();
        txtKategori = new javax.swing.JComboBox<String>();
        lblKepemilikan = new javax.swing.JLabel();
        txtKepemilikan = new javax.swing.JComboBox<String>();
        jLabel3 = new javax.swing.JLabel();
        btnProses = new javax.swing.JButton();
        btnCetak = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tableView = new javax.swing.JTable();

        setBorder(javax.swing.BorderFactory.createMatteBorder(5, 5, 5, 5, new java.awt.Color(99, 130, 203)));
        setTitle("Laporan Peminjaman Aset");

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        jPanel1.setPreferredSize(new java.awt.Dimension(721, 52));
        jPanel1.setLayout(new java.awt.BorderLayout());

        jToolBar1.setBorder(null);
        jToolBar1.setRollover(true);

        jLabel1.setText(" Tanggal : ");
        jToolBar1.add(jLabel1);

        txtTanggalAwal.setMaximumSize(new java.awt.Dimension(120, 29));
        txtTanggalAwal.setMinimumSize(new java.awt.Dimension(120, 29));
        txtTanggalAwal.setPreferredSize(new java.awt.Dimension(120, 29));
        jToolBar1.add(txtTanggalAwal);

        jLabel2.setText("s/d");
        jToolBar1.add(jLabel2);

        txtTanggalAkhir.setMaximumSize(new java.awt.Dimension(120, 29));
        txtTanggalAkhir.setMinimumSize(new java.awt.Dimension(120, 29));
        txtTanggalAkhir.setPreferredSize(new java.awt.Dimension(120, 29));
        jToolBar1.add(txtTanggalAkhir);

        jSeparator1.setMaximumSize(new java.awt.Dimension(5, 5));
        jSeparator1.setMinimumSize(new java.awt.Dimension(5, 5));
        jSeparator1.setPreferredSize(new java.awt.Dimension(5, 5));
        jSeparator1.setSeparatorSize(new java.awt.Dimension(5, 5));
        jToolBar1.add(jSeparator1);

        btnFilter.setText(">>");
        btnFilter.setFocusable(false);
        btnFilter.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnFilter.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnFilter.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFilterActionPerformed(evt);
            }
        });
        jToolBar1.add(btnFilter);

        lblKategori.setText(" Kategori : ");
        jToolBar1.add(lblKategori);

        txtKategori.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        txtKategori.setToolTipText("");
        txtKategori.setMaximumSize(new java.awt.Dimension(125, 29));
        txtKategori.setMinimumSize(new java.awt.Dimension(125, 29));
        txtKategori.setPreferredSize(new java.awt.Dimension(125, 29));
        txtKategori.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                txtKategoriItemStateChanged(evt);
            }
        });
        txtKategori.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtKategoriMouseClicked(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                txtKategoriMouseReleased(evt);
            }
        });
        txtKategori.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtKategoriActionPerformed(evt);
            }
        });
        txtKategori.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtKategoriKeyPressed(evt);
            }
        });
        jToolBar1.add(txtKategori);

        lblKepemilikan.setText(" Kepemilikan : ");
        jToolBar1.add(lblKepemilikan);

        txtKepemilikan.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        txtKepemilikan.setToolTipText("");
        txtKepemilikan.setMaximumSize(new java.awt.Dimension(180, 29));
        txtKepemilikan.setMinimumSize(new java.awt.Dimension(180, 29));
        txtKepemilikan.setPreferredSize(new java.awt.Dimension(180, 29));
        txtKepemilikan.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                txtKepemilikanItemStateChanged(evt);
            }
        });
        jToolBar1.add(txtKepemilikan);

        jLabel3.setText("  ");
        jToolBar1.add(jLabel3);

        btnProses.setText("Proses");
        btnProses.setFocusable(false);
        btnProses.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnProses.setMaximumSize(new java.awt.Dimension(100, 29));
        btnProses.setMinimumSize(new java.awt.Dimension(100, 29));
        btnProses.setPreferredSize(new java.awt.Dimension(100, 29));
        btnProses.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnProses.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnProsesActionPerformed(evt);
            }
        });
        jToolBar1.add(btnProses);

        btnCetak.setText("Cetak");
        btnCetak.setEnabled(false);
        btnCetak.setFocusable(false);
        btnCetak.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnCetak.setMaximumSize(new java.awt.Dimension(100, 29));
        btnCetak.setMinimumSize(new java.awt.Dimension(100, 29));
        btnCetak.setPreferredSize(new java.awt.Dimension(100, 29));
        btnCetak.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnCetak.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCetakActionPerformed(evt);
            }
        });
        jToolBar1.add(btnCetak);

        jPanel1.add(jToolBar1, java.awt.BorderLayout.CENTER);

        getContentPane().add(jPanel1, java.awt.BorderLayout.PAGE_START);

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder("Daftar Peminjaman Aset"));

        tableView.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Kode", "Nama Aset", "Kategori", "Qty", "Tanggal", "Kepemilikan", "Di input", "Keterangan"
            }
        ));
        jScrollPane1.setViewportView(tableView);
        if (tableView.getColumnModel().getColumnCount() > 0) {
            tableView.getColumnModel().getColumn(0).setPreferredWidth(135);
            tableView.getColumnModel().getColumn(0).setMaxWidth(135);
            tableView.getColumnModel().getColumn(2).setPreferredWidth(150);
            tableView.getColumnModel().getColumn(2).setMaxWidth(150);
            tableView.getColumnModel().getColumn(3).setPreferredWidth(50);
            tableView.getColumnModel().getColumn(3).setMaxWidth(50);
            tableView.getColumnModel().getColumn(4).setPreferredWidth(75);
            tableView.getColumnModel().getColumn(4).setMaxWidth(75);
            tableView.getColumnModel().getColumn(5).setResizable(false);
            tableView.getColumnModel().getColumn(6).setPreferredWidth(60);
            tableView.getColumnModel().getColumn(6).setMaxWidth(60);
        }

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 1008, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 255, Short.MAX_VALUE)
        );

        getContentPane().add(jPanel3, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnProsesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnProsesActionPerformed
        String valueTglAwal = ValueFormatter.getDateSQL(txtTanggalAwal.getDate());
        String valueTglAkhir = ValueFormatter.getDateSQL(txtTanggalAkhir.getDate());
        refreshDataPeminjaman(Date.valueOf(valueTglAwal), Date.valueOf(valueTglAkhir));
    }//GEN-LAST:event_btnProsesActionPerformed
    private void hideFilter() {
        lblKategori.setVisible(false);
        txtKategori.setVisible(false);
        lblKepemilikan.setVisible(false);
        txtKepemilikan.setVisible(false);
    }

    private void showFilter() {
        lblKategori.setVisible(true);
        txtKategori.setVisible(true);
        lblKepemilikan.setVisible(true);
        txtKepemilikan.setVisible(true);
    }
    private void btnCetakActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCetakActionPerformed
        if (daftarPeminjamanDetail.size() > 0) {
            try {
                String url = "/laporan/PeminjamanAset.jasper";
                Map<String, Object> map = new HashMap<>();
                map.put("tglAwal", txtTanggalAwal.getDate());
                map.put("tglAkhir", txtTanggalAkhir.getDate());
                map.put("pengguna", p.getNama());
                map.put("jabatan", p.getJabatan().toString());
                JasperPrint print = JasperFillManager.fillReport(
                        getClass().getResourceAsStream(url),
                        map,
                        new JRBeanCollectionDataSource(daftarPeminjamanDetail));
                JasperViewer view = new JasperViewer(print, false);
                view.setLocationRelativeTo(null);
                view.setExtendedState(JasperViewer.MAXIMIZED_BOTH);
                view.setVisible(true);
            } catch (JRException ex) {
                Logger.getLogger(LaporanSirkulasiAsetView.class.getName()).log(Level.SEVERE, null, ex);
            }
        } else {
            JOptionPane.showMessageDialog(this, "Data belum diproses", getTitle(), JOptionPane.INFORMATION_MESSAGE);
        }
    }//GEN-LAST:event_btnCetakActionPerformed

    private void btnFilterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFilterActionPerformed
        if (btnFilter.getText().equals(">>")) {
            btnFilter.setText("<<");
            showFilter();
        } else {
            btnFilter.setText(">>");
            txtKategori.setSelectedIndex(0);
            txtKepemilikan.setSelectedIndex(0);
            hideFilter();
        }
    }//GEN-LAST:event_btnFilterActionPerformed

    private void txtKategoriItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_txtKategoriItemStateChanged
//        refreshDataTablesWithFilter();
    }//GEN-LAST:event_txtKategoriItemStateChanged

    private void txtKategoriMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtKategoriMouseClicked

    }//GEN-LAST:event_txtKategoriMouseClicked

    private void txtKategoriMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtKategoriMouseReleased

    }//GEN-LAST:event_txtKategoriMouseReleased

    private void txtKategoriActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtKategoriActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtKategoriActionPerformed

    private void txtKategoriKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtKategoriKeyPressed

    }//GEN-LAST:event_txtKategoriKeyPressed

    private void txtKepemilikanItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_txtKepemilikanItemStateChanged
//        refreshDataTablesWithFilter();
    }//GEN-LAST:event_txtKepemilikanItemStateChanged

    public void refreshDataTables() {
        try {
            tableController.clearData();
            this.daftarPeminjamanDetail = repoPeminjaman.findPeminjamanByTglBetween(Date.valueOf(LocalDate.of(1990, 1, 1)), Date.valueOf(LocalDate.now()));
            for (PeminjamanDetail pd : daftarPeminjamanDetail) {
                Object[] row = {pd.getPeminjaman().getKode(), pd.getAset().getNama(), pd.getAset().getKategoriAset().getNama_kategori(),
                    pd.getQty(), ValueFormatter.getLocalDateShort(pd.getPeminjaman().getTanggal().toLocalDate()), pd.getAset().getKepemilikan().getNama(),
                    pd.getPeminjaman().getUser().getUsername(),
                    pd.getPeminjaman().getKet()};
                tableController.getModel().addRow(row);
            }
            tableController.setContentTableAlignment(Arrays.asList(0, 2, 3, 4, 5, 6));
        } catch (SQLException ex) {
            Logger.getLogger(LaporanAset.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    private void refreshDataPeminjaman(Date tglAwal, Date tglAkhir) {
        try {
            String kategori = txtKategori.getSelectedItem().toString();
            String kepemilikan = txtKepemilikan.getSelectedItem().toString();
            
            tableController.clearData();
//            daftarPeminjamanDetail = repoPeminjaman.findPeminjamanByTglBetween(tglAwal, tglAkhir);
            daftarPeminjamanDetail = repoPeminjaman.findPeminjamanByTglBetweenByKategoriByKepemilikan(tglAwal, tglAkhir, kategori, kepemilikan);
            if (daftarPeminjamanDetail.isEmpty()) {
                JOptionPane.showMessageDialog(this, "Tidak ada transaksi !", getTitle(), JOptionPane.INFORMATION_MESSAGE);
            }
            btnCetak.setEnabled(!daftarPeminjamanDetail.isEmpty());
            for (PeminjamanDetail pd : daftarPeminjamanDetail) {
                Object[] row = {pd.getPeminjaman().getKode(), pd.getAset().getNama(),
                    pd.getAset().getKategoriAset().getNama_kategori(),
                    pd.getQty(), ValueFormatter.getLocalDateShort(pd.getPeminjaman().getTanggal().toLocalDate()),
                    pd.getAset().getKepemilikan().getNama(),
                    pd.getPeminjaman().getUser().getUsername(),
                    pd.getPeminjaman().getKet()};
                tableController.getModel().addRow(row);
            }
            tableController.setContentTableAlignment(Arrays.asList(0, 2, 3, 4, 5, 6));
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(this, "Tidak dapat menampilkan data peminjaman", getTitle(), JOptionPane.ERROR_MESSAGE);
            Logger.getLogger(LaporanPeminjaman.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    private void refresDataKategoriAset() {
        try {
            txtKategori.removeAllItems();
            txtKategori.addItem("%");
            daftarKategori = repoKategori.findAll();
            for (KategoriAset ka : daftarKategori) {
                txtKategori.addItem(ka.getNama_kategori());
            }
            txtKategori.setSelectedItem("%");
        } catch (SQLException ex) {
            Logger.getLogger(LaporanPeminjaman.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    private void refresDataKepemilikan() {
        try {
            txtKepemilikan.removeAllItems();
            txtKepemilikan.addItem("%");
            daftarKepemilikan = repoKepemilikan.findAll();
            for (Kepemilikan ds : daftarKepemilikan) {
                txtKepemilikan.addItem(ds.getNama());
            }
            txtKepemilikan.setSelectedItem("%");
        } catch (SQLException ex) {
            Logger.getLogger(DataAsetView.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCetak;
    private javax.swing.JButton btnFilter;
    private javax.swing.JButton btnProses;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JToolBar.Separator jSeparator1;
    private javax.swing.JToolBar jToolBar1;
    private javax.swing.JLabel lblKategori;
    private javax.swing.JLabel lblKepemilikan;
    private javax.swing.JTable tableView;
    private javax.swing.JComboBox<String> txtKategori;
    private javax.swing.JComboBox<String> txtKepemilikan;
    private com.toedter.calendar.JDateChooser txtTanggalAkhir;
    private com.toedter.calendar.JDateChooser txtTanggalAwal;
    // End of variables declaration//GEN-END:variables

}
